### ISSUE TITLE
I want to create a jar with version 1.8 java

### ISSUE THREAD

**Issue by hashasnainalibohra123** [corunet/kloadgen#100]
I see some of the statements in the code is written in java 9. But my jmeter is compatible with 1.8 only.

Can you please suggest me how to create jar with 1.8

**Comment by kszosze** [comment]
This project had moved to java 11, since Java 8 is close to be in it's end of life (OpenJDK will end it in 10 months) so we prefer start moving it to Java 11 and use the improvements there.
I don't mind you want to make a fork and keep it in Java 8. But we will not chang it back to Java 8.

**Comment by M3lkior** [comment]
maybe you can change the compiler source in your forked project  to `1.8` on `compiler-maven-plugin ` ?
