### ISSUE TITLE
Request - Is there a possibility to provide ready to use JAR?

### ISSUE THREAD

**Issue by saini26rohit** [corunet/kloadgen#114]
Hi @manoncorunet,
I am very keen to use this utility to test Kafka with avro format messages. 
My organisation doesn’t allow to pull the codes from outside and use it. Is there a possibility that you can build the Jar and upload here in git hub so that people like me who are purely from testing background and have no knowledge how to create jar files or customise it, can use it. I can import it easily and use it.
Looking forward to use this.

Thanks in advance.

**Comment by kszosze** [comment]
Hi @saini26rohit,

Project can generate 2 jars, plugin one for running inside a JMeter installation and a standalone one to run it from command line. My guess is that you required the first one?

I can provide a Jar, but you still will need to drop it in the required folder, as appear in the instructions.

Regards.

**Comment by saini26rohit** [comment]
@kszosze Yes I will couple it with JMeter and will use it. Placing inside the JMeter that much I can do.
Appreciate the effort and help.

Thanks

**Comment by kszosze** [comment]
HI @saini26rohit ,

I added a way to provide a jar for you to able to test the plugin.
From now on the build action will deploy a jar in the github package repository, here is the url
https://maven.pkg.github.com/corunet/kloadgen/net/coru/kloadgen/3.5.1/kloadgen-3.5.1-kloadgen-plugin-3.5.1.jar

You just need to download it. 
Repository required authentication, as far as I know. You can get more info [here](https://stackoverflow.com/questions/64969548/how-to-download-a-jar-from-github-package-registry-for-a-specific-release-versio)

Cheers!!
