### ISSUE TITLE
Jmeter property function not taken in Config Element

### ISSUE THREAD

**Issue by M3lkior** [corunet/kloadgen#119]
Hi, i try ot use your plugin with the `$__P` function in order to externalize my kafka environment values, but it seems that the configuration don't get the jmeter parameters (see https://jmeter.apache.org/usermanual/functions.html#__P) : 

Here is my configuration  : 

![image](https://user-images.githubusercontent.com/5501911/131536917-43ab62be-fde4-4547-887b-d6ff2f4add8a.png)

Here is my jmeter command line 

```
 jmeter -JSCHEMA_REGISTRY_URL=<URL> -JCLUSTER_API_KEY=<API_KEY> -JCLUSTER_API_SECRET=<CLUSTER_API_SECRET>
```

This is working with other sampler / native jMeter config element

**Comment by M3lkior** [comment]
Thanks @kszosze ;

As a workaroung, it is possible to use an `User defined Variable` config with this kind of declarations 
![image](https://user-images.githubusercontent.com/5501911/132201104-d4a0ab4c-809c-4314-aab3-ae078843d9f7.png)

and use the variables keys in the KeyloadGen config with the `${key}` placeholder like this : 

```
![image](https://user-images.githubusercontent.com/5501911/132201212-3c1bde8e-8095-4ded-9020-545055b3bbf8.png)
```

Maybe you should just document this way for settings external configurations

**Comment by Rivarsal** [comment]
Hi @M3lkior,

I just looked into this issue and it was working fine on my end. I declared the properties in non-gui mode like this 

![image](https://user-images.githubusercontent.com/59642284/132229889-dc7b9581-cdcf-4107-8bd5-64780c38f40e.png)

And I declared the the properties on the Schema Config Registry Element like this:

![image](https://user-images.githubusercontent.com/59642284/132229945-78424460-65d6-4d24-9e2c-46c0eade721f.png)

Would it be too much if I ask you to give me your jmx so I can gladly look into it?

My best regards and I will be waiting for your answer.

**Comment by M3lkior** [comment]
Yes @Rivarsal it works on command line but not with the `Test Regsitry` button nor with the Load Avro Config which i guess need at least one connection from the GUI to load an avro schema from the registry

**Comment by Rivarsal** [comment]
Hello @M3lkior ! Sorry for the late answer, I was working on this. I added support to check the properties for both the Schema Registry field and the Schema Registry properties table in the 119 branch. Once we double check everything is correct we will merge it with master. 

Greetings!

**Comment by Rivarsal** [comment]
Hello @M3lkior 

Just wondering if everything is okay with the 119 branch?

Cheers and I hope you are having a good time!

**Comment by M3lkior** [comment]
hum ; i rapidly try to use your 3.5.3 version in my local env and the `Test Registry` button always throw the error: 

![image](https://user-images.githubusercontent.com/5501911/133118443-118d16de-e03b-4293-bc2a-05d55980e4ee.png)

**Comment by Rivarsal** [comment]
I think it might be one of this two things, if not I will check it and fix it ASAP. 

Have you set the SCHEMA_REGISTRY_URL with http:// or https protocol to yourServer ? If I don´t add the http it will throw an error since it has no protocol.

It worked on my end when I used it both on GUI using jmeter.bat -q file.properties and assigning the property from the console.

Let me know if that small solution worked, if not I will be glad to help you out.

**Comment by Rivarsal** [comment]
Hello @M3lkior 

Just checked your image again with @kszosze and we found out the issue. You wrote ${SCHEMA_REGISTRY_URL} which is a variable, instead of ${__P(SCHEMA_REGISTRY_URL)} which is the property.

This gave us an idea to support variables as well. I will work on that on the 119 branch and I will let you know when this is developed.

Greetings!

**Comment by M3lkior** [comment]
yes in fact i actually used the `User Defined Variables Config` to define all my external variables to use only properties on config : 

![image](https://user-images.githubusercontent.com/5501911/133232760-bbbb63c9-a5fc-484d-83fa-9d149f51034a.png)

I think you should handle those different approaches

**Comment by Rivarsal** [comment]
Hello again @M3lkior

We have investigated the way KloadGen and Jmeter Works and we have found out 2 solutions for these problem.

It will work if you use a **Property directly** on the Schema Registry Config Element andclick the **Test Registry Button** .We currently cannot make it work when you hit the **Test Registry button** if you use a **User Defined Variable**. 

You can also define the **User Defined Variables**, write the ${var} in the Schema Registry URL field and run the test. This will work as well if you already have the subjects charged in the Value Schema Load Generator Config.

Hope these solutions work for you.

Greetings.
