### ISSUE TITLE
Dealing with array of record in AVRO

### ISSUE THREAD

**Issue by M3lkior** [corunet/kloadgen#128]
Hi find this issue (https://github.com/corunet/kloadgen/issues/64) similar to my need but not satisfaisant answered or solutions 

I actually have in my main record an `array of records` field: 

```
{
   ... other fields
   {"name": "BusInputs",
            "type": {
                "type": "array",
                "doc": "Business units specifics datas needed to deduce BUs contexts.",
                "items": {
                    "name": "CostingRequestBUItem",
                    "namespace": "costingrequest",
                    "type": "record",
                    "fields": [
                        {"name": "ClientCode", "type": {"type": "string", "avro.java.string": "String"},
                        {"name": "ArrivalIncoterm", "type": ["null", {"type": "string", "avro.java.string": "String"}],
                        {"name": "ArrivalIncotermPlace", "type": {"type": "string", "avro.java.string": "String"},
                        ...
                    ]
                }
            }
        }
    ]
}

```

This structure is represented in the KLoadGen by the configuration below:

![image](https://user-images.githubusercontent.com/5501911/139033351-33e4f68c-da50-496b-98e9-3c7a989fadbe.png)

Here i find a way to generate many array items (5 in the example) with `BusInputs[5].ClientCode` but i need to be precise about each data in each array item.

Is there a sample of what i want to do (not possible currently)

![image](https://user-images.githubusercontent.com/5501911/139034407-77fe2fdb-993e-4286-8910-e4a9c8e538ee.png)

Do you have any solution or workaround ?

Thanks

**Comment by Rivarsal** [comment]
Hello @M3lkior

First of all, sorry for the late answer. We looked into it and we can make it process the values in FieldValueList as a sequence if you add something like {} instead of processing them randomly. I will create a branch and work on it since we think it´s a good feature to develop.

About this image, I don´t think we can make it possible that you can with the way it calculates sizes currently. I will still take a look into it and I will keep you updated.
![139034407-77fe2fdb-993e-4286-8910-e4a9c8e538ee](https://user-images.githubusercontent.com/59642284/140311491-a38eeb3c-ef12-4826-b30d-118065d374ff.png)

Cheers

**Comment by Rivarsal** [comment]
Hello! @M3lkior 

I just implemented a new change to the program in the branch  #128. If you type a fieldValueList with a "{" after the "[" like this: [{value1,value2] it will start a sequence between value1 and value2 instead of doing it randomly.

Greetings

**Comment by M3lkior** [comment]
Hello @Rivarsal ; thanks for your reactivity, i must not add a `}` to close the sequence ?

So for my example i must do a think like

`BusInputs[].cliendCode | [{1,2]` will generate two entries with a clientCode 1 and next a clientCode 2 ?

**Comment by Rivarsal** [comment]
Yeah, you don´t have to write "{" at the end of it. Just at the beginning.

Let me take a look into your problem. I believe this is happening because of this issue: #130 which is fixed but hasn´t been implemented on to master yet.  

I will check it and I will give you an answer ASAP.

**Comment by Rivarsal** [comment]
Just checked and the Issue #130 will take a little longer, the PR it´s on draft currently since they found new problems with the Enum generation.

**Comment by M3lkior** [comment]
For information, i tried to merge the #130 on my local #128 branch to test the fix but i have the same issue

**Comment by Rivarsal** [comment]
We have to fix the #130 issue. We will take a look into it.

**Comment by Rivarsal** [comment]
Hello @M3lkior !

After days of developing we have found what looks like a solution for the sequences and the Enum problem, it´s ready to be reviewed in #135 and it will ship to master once it´s revised.

Sorry for the delays and I hope it works for you

**Comment by M3lkior** [comment]
Hey @Rivarsal ; no worries :) i will test this pr this day and give you a feedback :)

**Comment by M3lkior** [comment]
hi @Rivarsal , i test this enhancement today in my jMeter project;

it works like expected in my usecase; thanks a lot !

**Comment by M3lkior** [comment]
Hi @Rivarsal ; how are you ?

I migrate my jMeter KLoadGen script with real business data and i found a bug with the sequence feature

You can easily reproduce with those valueLists:

Given:
```
BusInputs[18].ClientCode ->  "{1, 2, 3, 5, 6, 7, 7, 9, 9, 9, 10, 14, 17,17, 17, 17, 18, 19, 20"
BusInputs[18].ArrivalIncoterm -> "{DDP, CIF, DDP, CIF, CIF, CFR, CFR, CIF, CIF, , CIF, DDP, CIF, CIF, CIF, DDP, CIF, CIF, CIF"
BusInputs[18].ArrivalIncotermPlace -> "{FRDGS, ESVLC, PTPSI, ITGOA, PLGDY, BRSSZ, BRSSZ, RUVYP, LVRIX, , ITGOA, FRMAC, FRLEH, GPPTP, REPDG, FRCGI, ESVLC, GRPIR, PLGDY"
```

When a list contains some value multiple time, your algorithm below seems to have a weird behavior: 
```
 return ValueUtils.castValue(
            context.compute(fieldName, (fieldNameMap,
                                        seqObject) -> seqObject == null ? fieldValueList.get(0)
                    : seqObject.toString().equals(fieldValueList.get(fieldValueList.size()-1)) ? fieldValueList.get(0) : fieldValueList.get(fieldValueList.indexOf(seqObject)+1)),
            fieldType);
```

- after the first `7` value found and processed in the `BusInputs[18].ClientCode `, all the others values are set to `7`
- concerning the `BusInputs[18].ArrivalIncoterm`, the value set is an alternation between `DDP` and `CIF`  the first `7` value found and processed in the `BusInputs[18].ClientCode `, all the others values are set to `7`
- and for the `BusInputs[18].ArrivalIncotermPlace `, the assignation restart at position 0 after processing the first `PLGDY`

I try to fix the issue, but this is complex for me to understand the full implementation

Thanks in advance !

**Comment by Rivarsal** [comment]
Oh! Sorry for that @M3lkior 

I will pass this to our team since I will be on holidays this week. Most of us are on holidays so the fix for this might be delayed a little. My apologies in advance

**Comment by kszosze** [comment]
Hi @M3lkior,

Logic was a bit confused. I´ll check it and rework it a bit.
Can you please try if the new brand #128  works for you?

Keep in mind, regarding you last scenario, if you define an array size bigger than values it will restart from the init.

Cheers

**Comment by M3lkior** [comment]
Oh thanks for your reactivity; i test your fix this morning !

> Keep in mind, regarding you last scenario, if you define an array size bigger than values it will restart from the init.
> 

Yes i agree and it is for me an expected comportment :)

**Comment by M3lkior** [comment]
It is ok @kszosze ! Thanks for the quick fix !!
