### ISSUE TITLE
A new release

### ISSUE THREAD

**Issue by harjis** [corunet/kloadgen#134]
Hi!

First of all thanks for the work you have put into this plugin. It is highly appreciated 👍 We use this plugin in creating a JMeter docker image. Currently the only working solution we have found is pulling master and then compiling the .jar during image build time. I was wondering if you could make a more recent release which we could use instead of pulling master?

I saw that you keep the packages in Github Packages where more recent versions (3.5.3, 3.5.1 e.g.) are available. I tried downloading these as well but it seems that Github requires authentication even for public packages.

**Comment by Rivarsal** [comment]
Hello @harjis!

We are aware of this issue, and we will add Kloadgen´s jars to Maven in the future. 

We will keep you updated when it happens, sorry for the inconveniences.

Cheers!

**Comment by armando-montoya-kr** [comment]
@Rivarsal could it be an option that we have a github workflow that creates a jar file under the github releases page upon a new tag created?
I could contribute with that work if that suits the plugin work.

**Comment by kszosze** [comment]
Hi @armando-montoya-kr,

thanks for the offer.

We already have an action which upload the latest build from master into github package, but to download it, you need some authentication. It order to make more accessible we are working to make our release in Maven Central, so it will be more easy to download the jars.

Cheers!!

**Comment by jemacineiras** [comment]
Close due inactivity
