### ISSUE TITLE
Array of Map 

### ISSUE THREAD

**Issue by UjavalMehta** [corunet/kloadgen#154]
Hi Team,
My Avro Schema Template look like:
{
         "name":"customerIdentifiers",
         "type":[
            "null",
            {
               "type":"map",
               "values":{
                  "type":"array",
                  "items":"string"
               }
            }
         ],
         "doc":"identifiers of the customer",
         "default":null
      }
      

With PepperBox plugins, Its like:
"customerIdentifiers": {
   	"map" : {
   		"accountIds": ["${TENANT_ID}"],
   		"phoneNumbers": ["98${MobileNO}"],
   		"emailAddresses": ["autocust1${USER_PREFIX}${__threadNum}@fs1lab.com"]
   	}
   }
   
   
   While migrating into kloadgen (kloadgen-3.5.2.jar), I am using below:
   {accountIds:[${TENANT_ID}], phoneNumbers:[98${MobileNO}], emailAddresses:[autocust1${USER_PREFIX}${__threadNum}@fs1lab.com]}
   
![image](https://user-images.githubusercontent.com/91044482/148900786-dcefa6fe-a835-4e3d-8129-17c92777b582.png)

Above things is not working and getting me into below error in jmeter log file:
2022-01-11 07:34:20,007 ERROR o.a.j.p.j.s.AbstractJavaSamplerClient: Failed to send message
org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"map","values":{"type":"array","items":"string"}}]: array-map (field=customerIdentifiers)
at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:223) ~[kloadgen-3.5.2-kloadgen-plugin-3.5.2.jar:?]

Please suggest how to resolve this

**Comment by Rivarsal** [comment]
@UjavalMehta I will look into this and I will give you an answer soon. 

Sorry for the troubles!

**Comment by UjavalMehta** [comment]
ThnQ Rivarsal

**Comment by Rivarsal** [comment]
Hello @UjavalMehta 

I am seeing that you are using 3.5.2 version of KloadGen. 

Could you please change to this branch #149 and try it out with this changes? Your version doesn´t use the AvroGeneratorTool class that support unions. If it doesn´t work with that I will still take a look!

Sorry for the troubles. 

Cheers!

**Comment by UjavalMehta** [comment]
ok 
Let me try with latest jar
ThnQ

**Comment by UjavalMehta** [comment]
I tried to clone the repository
https://github.com/corunet/kloadgen.git

While jar creation, Its failing for me:
![image](https://user-images.githubusercontent.com/91044482/148956716-4dd8ab3e-22d0-4dd3-a05d-f6e8842a6a68.png)


Will it be possible to share the jar to use if you have?

**Comment by Rivarsal** [comment]
Please let me know when you downloaded the file so I can take down the link

https://mega.nz/folder/V18lQYLQ#O6kirlCcpIlEUZ-mOZRQcA

**Comment by UjavalMehta** [comment]
I can able to download the file...
Thank You
I will try and will update you

**Comment by UjavalMehta** [comment]
I am having the same Error
2022-01-12 06:25:05,635 ERROR o.a.j.p.j.s.AbstractJavaSamplerClient: Failed to send message
org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"map","values":{"type":"array","items":"string"}}]: a
ccountIds:[QVOQMV] (field=customerIdentifiers)

![image](https://user-images.githubusercontent.com/91044482/149075540-c2bc47d6-f696-4a3d-b27d-a3dc28305bea.png)

**Comment by Rivarsal** [comment]
Okay, then I will run some more tests and check what's wrong. Could you give me a more detailed Avro? Sorry for the trouble

**Comment by UjavalMehta** [comment]
{
   "type":"record",
   "name":"CreateInboundEngagement",
   "namespace":"com.xxxxx.xxxxxx.avro",
   "doc":"Command to create an inbound engagement",
   "fields":[
      {
         "name":"tenantId",
         "type":"string",
         "doc":"the unique identifier for the tenant"
      },
      {
         "name":"clientSessionId",
         "type":[
            "null",
            "string"
         ],
         "doc":"the unique identifier for the session",
         "default":null
      },
      {
         "name":"engagementId",
         "type":[
            "null",
            "string"
         ],
         "doc":"the unique identifier for the engagement",
         "default":null
      },
      {
         "name":"dialogId",
         "type":[
            "null",
            "string"
         ],
         "doc":"the unique identifier for the dialog",
         "default":null
      },
      {
         "name":"channelProviderId",
         "type":"string",
         "doc":"the unique identifier for this channel provider"
      },
      {
         "name":"businessAccountName",
         "type":[
            "null",
            "string"
         ],
         "doc":"business account configured on provider, on which the message came in or using which the message will be sent out",
         "default":null
      },
      {
         "name":"providerDialogId",
         "type":[
            "null",
            "string"
         ],
         "doc":"the unique identifier of the dialog generated by provider",
         "default":null
      },
      {
         "name":"conversation",
         "type":[
            "null",
            "string"
         ],
         "doc":"the conversation to which this engagement belongs",
         "default":null
      },
      {
         "name":"channelId",
         "type":"string",
         "doc":"Identifier of the channel"
      },
      {
         "name":"customerIdentifiers",
         "type":[
            "null",
            {
               "type":"map",
               "values":{
                  "type":"array",
                  "items":"string"
               }
            }
         ],
         "doc":"identifiers of the customer",
         "default":null
      },
      {
         "name":"externalParticipantId",
         "type":[
            "null",
            "string"
         ],
         "doc":"the unique identifier for the external participant",
         "default":null
      },
      {
         "name":"sessionParameters",
         "type":{
            "type":"map",
            "values":[
               "null",
               "string"
            ],
            "default":null
         },
         "doc":"other information user"
      },
      {
         "name":"engagementParameters",
         "type":{
            "type":"map",
            "values":[
               "null",
               "string"
            ],
            "default":null
         },
         "doc":"additional information for engagement"
      },
      {
         "name":"providerSenderParticipantId",
         "type":[
            "null",
            "string"
         ],
         "doc":"the unique identifier for the request that triggered this event or command. This should be referenced when notifying a related error",
         "default":null
      },
      {
         "name":"id",
         "type":"string",
         "doc":"a unique id for the current event"
      },
      {
         "name":"correlationId",
         "type":[
            "null",
            "string"
         ],
         "doc":"the unique identifier for the request that triggered this event or command. This should be referenced when notifying a related error",
         "default":null
      },
      {
         "name":"timestamp",
         "type":{
            "type":"long",
            "logicalType":"timestamp-millis"
         },
         "doc":"timestamp (milliseconds since epoch) when the event was generated"
      },
      {
         "name":"displayName",
         "type":[
            "null",
            "string"
         ],
         "doc":"the display name of the customer as visible on interaction window",
         "default":null
      }
   ]
}

**Comment by UjavalMehta** [comment]
Above one is the avro schema
I am unable to attach the json file so I have pasted schema here
Please upload the same schema json file on Value Schema File Load Generator Config

**Comment by Rivarsal** [comment]
So we have tried with your AvroSchema manually(by creating an avro file with it) and we are seeing different values being extracted into our FieldType. 

![AvroFieldValueMappingList](https://user-images.githubusercontent.com/59642284/149090174-701ef49b-094d-43cb-ad18-08fb1446f3ff.png)

We have tried with this setup and it works totally fine, with variables and functions. I think your issue is happenning due to the conversion from PepperBox. We suggest if it´s possible to do it by creating your avro file manually and pasting the schema generated.

**Comment by UjavalMehta** [comment]
Yeah I have created Avro file manually and It look working fine for 10 events and I blocked with this events
But Thank you for the quick update, Let me try this from my end

**Comment by Rivarsal** [comment]
Okay! Will be waiting for your answers.

Also, thanks to this issue we have found that sequences are not being generated right, so thank you for that and we will fix that right away since it´s an easy fix.

**Comment by UjavalMehta** [comment]
with kloadgen-3.5.2, It was generating parameter from json file wrongly.
I have uploaded json again with kloadgen-3.6.2 and It look like what you have given above and now its passing for me

Thanks lot for quick help :) 

There are 2 things, I wanted to highlight.
Please let me know whether I need to created another issue for that or here it should be ok
1) whenever we have multiple producer events in same script, It showing below warning in jmeter logs:
2022-01-12 09:08:23,050 WARN o.a.k.c.u.AppInfoParser: Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.producer:type=app-info,id=
at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436) ~[?:?]
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1865) ~[?:?]
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:960) ~[?:?]
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:895) ~[?:?]
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320) ~[?:?]
at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:523) ~[?:?]
at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:64) [kloadgen-3.6.2-kloadgen-plugin-3.6.2.jar
:?]
at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:434) [kloadgen-3.6.2-kloadgen-plugin-3.6.2.jar:?]
at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:291) [kloadgen-3.6.2-kloadgen-plugin-3.6.2.jar:?]
at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:318) [kloadgen-3.6.2-kloadgen-plugin-3.6.2.jar:?]
at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303) [kloadgen-3.6.2-kloadgen-plugin-3.6.2.jar:?]
at net.coru.kloadgen.sampler.KafkaSchemaSampler.setupTest(KafkaSchemaSampler.java:112) [kloadgen-3.6.2-kloadgen-plugin-3.6.2.ja
r:?]
at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) [ApacheJMeter_java.jar:5.4.1]
at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.1]
at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.1]
at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.1]
at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.1]
at java.lang.Thread.run(Thread.java:833) [?:?]


2) For above avro event, I can see its not creating correct request from jmeter log point of view....From lab point of view, It looks passing but wanted to understand more. Also some of the Jmeter inbuild(getIteration()) function is not working here like below:
![image](https://user-images.githubusercontent.com/91044482/149099332-4ff0026c-14bb-46af-8b07-33a1ae18d95d.png)

**Comment by Rivarsal** [comment]
Glad to hear that it kinda worked! 

For the next 2 problems:

1. I would create a new issue for this. I am not sure if we support multiple producers, I need @kszosze help on this one. 

2.  I need more explanation on the second one. What is it that is not being created correctly? Let me check if I can find a way to make the inbuilt function work since it´s tricky to work with them.

**Comment by UjavalMehta** [comment]
Thanks Rivarsal for quick note
for 2 point. Screen is the output of the request which I tried to produce with above json

Please let me know If you need any more details

**Comment by Rivarsal** [comment]
![image](https://user-images.githubusercontent.com/59642284/149117532-117997a9-3365-4f22-9d6e-0816cd9f233a.png)

I managed to get the function getIteration working in this way:

![image](https://user-images.githubusercontent.com/59642284/149117729-4021b9a2-446e-48ac-a5c8-d772520152e3.png)

**Comment by UjavalMehta** [comment]
That's cool
Thank You 👍
