### ISSUE TITLE
Need to set min.insync.replicas and replication factor

### ISSUE THREAD

**Issue by kszosze** [corunet/kloadgen#160]
### Discussed in https://github.com/corunet/kloadgen/discussions/159

<div type='discussions-op-text'>

<sup>Originally posted by **ramandas30** January 14, 2022</sup>
Hi,
my scenario is i want to create topic having min.insync.replicas 2 and replication factor atlst 2.
there are 5 broker is running in my kafka cluster</div>

**Comment by kszosze** [comment]
Hi @ramandas30,

I was checking out the discussion you opened and saw those properties you need are Broker configuration properties. What you need to set up in the producer is the _acks_ property, following the official documentation..

> The number of acknowledgments the producer requires the leader to have received before considering a request complete. This controls the durability of records that are sent. The following settings are allowed:
> 
>   ***acks=0*** If set to zero then the producer will not wait for any acknowledgment from the server at all. The record will be immediately added to the socket buffer and considered sent. No guarantee can be made that the server has received the record in this case, and the retries configuration will not take effect (as the client won't generally know of any failures). The offset given back for each record will always be set to -1.
>
>   ***acks=1*** This will mean the leader will write the record to its local log but will respond without awaiting full acknowledgement from all followers. In this case should the leader fail immediately after acknowledging the record but before the followers have replicated it then the record will be lost.
>
>  ***acks=all*** This means the leader will wait for the full set of in-sync replicas to acknowledge the record. This guarantees that the record will not be lost as long as at least one in-sync replica remains alive. This is the strongest available guarantee. This is equivalent to the acks=-1 setting.

Do you need to us to support any specific producer property?

**Comment by jemacineiras** [comment]
Closing due inactivity.
