### ISSUE TITLE
kloadgen passing null value to Key

### ISSUE THREAD

**Issue by UjavalMehta** [corunet/kloadgen#169]
With kLoadGen:
![image](https://user-images.githubusercontent.com/91044482/151334396-9354c2b1-555c-4a9a-8770-cea0500e629d.png)

With PepperBox:
![image](https://user-images.githubusercontent.com/91044482/151334473-2837b1d7-57bc-4728-924d-f8c759192d69.png)

I am using kloadgen-3.6.2.jar
I cannot see below parameter for kloadGen Java Request:
1) keyed.message
2) message.key.placeholder
3) message.value.placeholder

message.key.placeholder will be useful to pass Key parameter rather than passing "null" value to Key

Please help me how to resolve the issue

**Comment by kszosze** [comment]
HI @UjavalMehta,
I'll take a look into it.

Cheers!

**Comment by UjavalMehta** [comment]
Thank You

**Comment by UjavalMehta** [comment]
After using "Key Plain Load Generator Config", I can see Key is passing but it looks like different behavior to me.
I am using "${engagementId}_${__BeanShell(vars.getIteration();)}".
There are 10+ kLoadGen java request events where few events getting getIteration "0" and few getting "1" which looks weird with "Key Plain Load Generator Config".
Same I have used in "Value Schema File Load Generator Config" which is passing correct.
Event 1 of event is triggering 2 times (1 with Key=EngagementId_0 and 2nd with Key=EngagementId_1)
Weird behavior to me


Providing some screen below:
![image](https://user-images.githubusercontent.com/91044482/151745019-5b362aaa-199e-46c7-8b8e-9f22f582b246.png)

![image](https://user-images.githubusercontent.com/91044482/151745055-0684e62a-4f05-4774-ade4-57ec4f222ab7.png)

From Jmeter Logs...1 event for CoachComplete
![image](https://user-images.githubusercontent.com/91044482/151745131-a947ef07-3b45-44df-bd06-be7e3431109e.png)

From Application Logs ... 2 event for CoachComplete
![image](https://user-images.githubusercontent.com/91044482/151745496-6d0ea053-094f-4beb-a036-c204305d8aa3.png)

**Comment by UjavalMehta** [comment]
@kszosze , @Rivarsal , 
Please let me know If you need call to understand more into this but will be needing your assistance as soon as you can manage time.

**Comment by jemacineiras** [comment]
HI @UjavalMehta,

I will need to see the `jmx` you are using in order to see how you had configured the test plan. The `getIteration` function will provide the count of the loop inside the Thread. So please attach the `jmx` file.

Regarding
`
    keyed.message
    message.key.placeholder
    message.value.placeholder
`
First one is set in the Sampler properties table.
The other 2 we are not using them. Where had you seen then?

Cheers

**Comment by UjavalMehta** [comment]
Due to security concern, I won't be able to share the jmx
But below is the screen like how I have configured the test plan:
![image](https://user-images.githubusercontent.com/91044482/151761354-dff9700a-c689-4571-ab9f-1704d09898f9.png)

Header is : Kafka Header Config Element
Message is : Value Schema File Load Generator Config
4_0 or like that pattern is : Java Request for kLoad Gen Producer Schema
Schema is : Schema Registry Config Element
Parameter is : Key Plain Load Generator Config

Regarding
keyed.message message.key.placeholder message.value.placeholder
I can't see those parameter with kloadGen 3.6.2 jar
![image](https://user-images.githubusercontent.com/91044482/151761794-791e3e74-88bc-4022-9c57-ff619364fac1.png)
![image](https://user-images.githubusercontent.com/91044482/151761837-303745a5-04fc-44c3-b3a0-c6b1d9ebdf17.png)

**Comment by jemacineiras** [comment]
Hi @UjavalMehta,
I see, the `keyed.message` property you can see in the documentation had been removed in favour of use of the Key Serialized Config Elements. I forgot to remove that in the configuration. Meaning that it's automatically set to true when you add one of those components, if not null is used by default, so no key is generated and sent.
The same happens with the `message.placeholder.key`, is a problem in the documentation.
My apology for that.
Regarding the `getIterator` thing, I need to see how you configure the Thread group. If you can provide a snapshot of these properties, it will help me.

Cheers

**Comment by UjavalMehta** [comment]
Thank You Joes
I am unable to see the "Key Serialized Config Elements" with kloadGen 3.6.2. 
I am using "Schema Registry Config Element" whether that will fulfil the Keyed.message propperty to Yes or not
![image](https://user-images.githubusercontent.com/91044482/151771954-7aeb7533-457e-4617-acd5-bc80362cddd6.png)


Regarding @getIterator, 
![image](https://user-images.githubusercontent.com/91044482/151772067-550b8712-ad8b-4281-a41a-8557becfc16a.png)
THREAD_COUNT, RampUpTime, LoopCount is set to 1 for this sanity checks.

**Comment by jemacineiras** [comment]
Hi @UjavalMehta,

to configure the key, you should use one of the `Key Schema` or the `Key Plain` one. Key Plain Load Generator Config will let you configure a simple message key. The others will create a key defined by a schema.
![Key components](https://user-images.githubusercontent.com/68995937/151772946-00506769-a5a4-4180-b4eb-66c6efdb57ec.png)
We still need to work a bit in the component naming.
Sorry for that.

Regarding the iterator number, is the matter of how Jmeter works under the hood. Giving those values, it should work as you expect. We are not interfering in the Jmeter behaviour.

**Comment by UjavalMehta** [comment]
I have start using "Key Plain Load Generator Config" and stopping using the ${BeanShell(vars.getIteration(); )}

Its working for me but I would recommend to have keyed.message message.key.placeholder message.value.placeholder parameter with "net.coru.kloadgen.sampler.KafkaSchemaSampler" class within Java Request which help to remove the complexity.

Thanks a lot for your support
