### ISSUE TITLE
String-Map - Send preset values

### ISSUE THREAD

**Issue by muthiahm227** [corunet/kloadgen#18]
Currently we are required to send 20+ key-value pairs (preset values and not random values) as part of the String-Map field and what we have observed is that the plugin randomly chooses a few key-value pairs and sends it to Kafka Topic. Is it possible to change the behavior of this to send the preset-value as it is, if the Field-Length value is set to "0"?

**Comment by kszosze** [comment]
Hi Muthiahm,
we are gonna implement this behaviour in the same way the arrays works.
We shall keep some coherence with the other similar functionalities.
Regards

**Comment by muthiahm227** [comment]
Thanks, will wait for the updated code.

**Comment by kszosze** [comment]
Hi Muthiahma,
 we are working in a solution,
 I hope quite soon we are gonna deliver something.
Regards

**Comment by muthiahm227** [comment]
Sure, thanks for the update

**Comment by codigoFuentes** [comment]
Hi Muthiahm,
the update is ready you can test it directly from the master branch.
Regards
