### ISSUE TITLE
[Issue]: Changelog not visible in repo

### ISSUE THREAD

**Issue by esthertrigo** [corunet/kloadgen#195]
### What happened?

According to the GH action _Generate changelog_ log, the changelog gets generated but it does not show in the repository.

This page might help solving the issue: https://github.com/heinrichreimer/action-github-changelog-generator/issues/22

### KloadGen Version

KLoadGen 3.0

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by jemacineiras** [comment]
Changelog generated as part of Github Release procedure
