### ISSUE TITLE
[Issue]: Issue with subsequence and defaults in Avro Schema

### ISSUE THREAD

**Issue by JonasMueller1991** [corunet/kloadgen#208]
### Issue with subsequence and defaults in Avro Schema
Hey,
I found a new strange behavior in an Avro schema. 
A minimal example for the Avro schema is attached.
Note that there are two fields `valueWithDefaults` and `valueWithoutDefaults`, where one of them has a default value in `type`. If we use this Avro schema in the Value Schema Load Generator Config and use the field type `seq` to send a subsequence (let's say [a,b,c]) the resulting Kafka message reads:

a -> b -> c for the case without defaults

However, 

seq -> seq -> seq for the case with defaults (see in relevant log output). 

I attached the minimal testplan and avro schema.

Again thanks in advance,
Jonas

.jmx and .avsc were not supported 😅 
[issue.avsc.txt](https://github.com/corunet/kloadgen/files/8465045/issue.avsc.txt)
[issue.jmx.txt](https://github.com/corunet/kloadgen/files/8465046/issue.jmx.txt)

### KloadGen Version

4.0.4

### Relevant log output

```shell
genericRecord={"data": {"RecordArray": [{"valueWithDefaults": "seq", "valueWithoutDefaults": "a"}, {"valueWithDefaults": "seq", "valueWithoutDefaults": "b"}, {"valueWithDefaults": "seq", "valueWithoutDefaults": "c"}]}}
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by cmunozgomez** [comment]
Hi @JonasMueller1991 

Thank you for your collaboration, we will review it and the changes/progress that we are making will inform you here.

**Comment by cmunozgomez** [comment]
hi @JonasMueller1991,

we have detected the problem of the incorrect behavior in the cases of sequences. 

We will open a pull request for the change to be integrated into the main branch. When said pull request is closed, this issue will be concluded initially.

As soon as we have the changes uploaded to the branch and the pull request created by @fcampostato , we will indicate it here. 

Again thank you very much for your collaboration.

**Comment by JonasMueller1991** [comment]
Thanks! :)

**Comment by fcampostato** [comment]
Hi @JonasMueller1991,

We've being working on this today and we've uploaded a solution for this.
You can check and try it on the [#208-sequence-and-defaults](https://github.com/corunet/kloadgen/tree/%23208-sequence-and-defaults) branch.

We are still working on it, so it can take a little to be deployed to master.
If you find any problems with the solution, please come back and we will try to help you.

Cheers!

**Comment by cmunozgomez** [comment]
hi @JonasMueller1991,

the pull request associated with this issue was integrated into the main branch, therefore this issue is closed.

Again, thank you very much for your collaboration.
