### ISSUE TITLE
[Documentation Issue]: Sequence segment needs to be changed

### ISSUE THREAD

**Issue by Rivarsal** [corunet/kloadgen#214]
### What's the problem folk?

@cmunozgomez found out that the sequence segment is outdated. It needs to be changed to the current version.

![image](https://user-images.githubusercontent.com/59642284/163969746-50a3f376-a13e-4159-a6b8-e29f948dd118.png)

### Have you checked that this is on the documentation already?

- [X] I have already checked the documentation

### Have you checked that this issue is being taken care of already?

- [X] I have already checked that this issue is being taken care of.

**Comment by cmunozgomez** [comment]
hi @esthertrigo 

both in schemas.md and in the wiki, those references to the use of "{" in the paragraph that explains the use of sequences must be eliminated, only remains that "seq" is used in the Field Type.
