### ISSUE TITLE
Change FieldValueMapping attribute name to one closer to the logic of its use.

### ISSUE THREAD

**Issue by cmunozgomez** [corunet/kloadgen#216]
### What happened?

add support for change the isParentRequired attribute to isAncestorRequired.
When this change is made, it must be revised in all the places where said attribute is used with the previous name, in the variables and methods where implicit logic is used or referenced (for example: method names, variables, etc)

### KloadGen Version

KloadGen 4.0.0

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by IsaUlloa** [comment]
Hi @cmunozgomez, we have changed the name of the attribute "isParentRequired" for "isAncestorRequired".
