### ISSUE TITLE
refactor the AvroExtractor class

### ISSUE THREAD

**Issue by cmunozgomez** [corunet/kloadgen#217]
### What happened?

add support for the refactor and revision of the AvroExtractor class.
The idea is to eliminate the repeated methods that use the same logic and they only differ by the use of the control logic of the isParentRequired variable (in another issue it has already been requested to change it to isAncestorRequired). Also eliminate those unused methods.

### KloadGen Version

KloadGen 4.0.6

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by pedror19** [comment]
Hi @cmunozgomez, we have refactored the AvroExtractor class and created a new one with some common utils for all the extractor classes.
