### ISSUE TITLE
 apply the CorunetStyle  in Code Style and the text justification in the .avsc test files

### ISSUE THREAD

**Issue by cmunozgomez** [corunet/kloadgen#218]
### What happened?

add support to justify and review the style of the .avsc test files by applying the CorunetStyle to these files.

### KloadGen Version

KloadGen 4.0.6

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by pedror19** [comment]
Hello @cmunozgomez  we have fixed the styles
