### ISSUE TITLE
[Issue]: Changed KloadGen plugin´s generated files name

### ISSUE THREAD

**Issue by Rivarsal** [corunet/kloadgen#221]
### What happened?

Currently, KloadGen files are generated as such: 
![image](https://user-images.githubusercontent.com/59642284/165283034-4b7fe1b7-1168-46d8-9774-00e7d6546d21.png)
![image](https://user-images.githubusercontent.com/59642284/165283092-b169bdc1-1c81-44aa-8539-56988ea9282d.png)

These names might create a little bit of confusion to new users. A suggestion from @esthertrigo is to add "KLG" in front of the files in order to make it more clear. For Example:  KLG - Value Schema Deserializer Config.

### KloadGen Version

KloadGen 4.0.8

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by IsaUlloa** [comment]
Hi @Rivarsal ,

We have changed the plugin's generated files names.
