### ISSUE TITLE
[Issue]: Fix Typo: Constrains in FieldValueMapping

### ISSUE THREAD

**Issue by Rivarsal** [corunet/kloadgen#222]
### What happened?

Currently, FieldValueMapping.class and FieldValueMappingBuilder have a variable called **constrains**.

![image](https://user-images.githubusercontent.com/59642284/165284559-04a42aca-a197-45b9-91b8-5a725a86241f.png)

This is a typo, the correct spelling is **constraints**. This also happens in the methods getConstrains, setConstrains.

### KloadGen Version

KloadGen 4.0.8

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by pedror19** [comment]
Hi @Rivarsal we have reviewed and fixed the typo
