### ISSUE TITLE
[Issue]: Field list values with JMeter variables may be treated as sequence and field lists depending on the number of values

### ISSUE THREAD

**Issue by t-h-e** [corunet/kloadgen#242]
### What happened?

I noticed another bug in the `seq` implementation in combination with JMeter variables.

Assume we have the following field value mapping:
```
data[${amount}].intFieldValueList | seq | 0 | [${intFieldValueList}]
```
Note that is now int rather than string.

Lets assume we have a loop around the KafkaSchemaSampler as in the example attached to this issue.
The following table represents three iterations (each row is one iteration), and shows the values of the variables and the output.
| ${intFieldValueList} | ${amount} | output |
|--|--|--|
| 1 | 1 | {"data": [ { "intFieldValueList": 1 } ] } |
| 5,6 | 2 | {"data": [ { "intFieldValueList": 5 }, { "intFieldValueList": 6 } ] } |
| 9 | 1 | {"data": [ { "intFieldValueList": 2 } ] } |

The issue is the following.
- In the first iteration, `intFieldValueList` is treated as sequence with the start value `1` which results in output `1`
- In the second iteration `intFieldValueList ` is treated as field value list and the sequence values do not matter. The output is `5` and `6` as the field value list specifies two values that are used.
- In the third iteration, the problem occurs as the field value list contains only a single value and therefore is treated as sequence again. As the previous values was `1`, the next is `2`, even though `9` was specified.

As suggested in another issue or PR, there should be a clearer distinction between sequence and field value list.

[FieldValueListBug.jmx.txt](https://github.com/corunet/kloadgen/files/8639678/FieldValueListBug.jmx.txt)
[FieldValueListBug.avsc.txt](https://github.com/corunet/kloadgen/files/8639679/FieldValueListBug.avsc.txt)

### KloadGen Version

4.0.9

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by IsaUlloa** [comment]
Hi @t-h-e ,

Thank you for you collaboration, we will look into it.

**Comment by IsaUlloa** [comment]
Hi @t-h-e ,

Since what you are trying to do is not compatible with our sequences logic, we decided to create a new field type called "Iterator".

We are working on it, so soon we hope to have the problem solved.

**Comment by IsaUlloa** [comment]
Hi @t-h-e ,

We have implemented the new type of field 'it'. There is a branch linked to this issue where you can try the changes.

**Comment by IsaUlloa** [comment]
Hi @t-h-e ,

We have made some changes to this new field. You can now check it out and tell us if it has solved your problem.

**Comment by IsaUlloa** [comment]
Since there is no answer and all the changes related with this problem are merged, we proceed to close this issue.
