### ISSUE TITLE
[Protobuf issue with Date and Time parameterization]: 

### ISSUE THREAD

**Issue by nrellanti** [corunet/kloadgen#255]
### What happened?

**Issue with Date and Time parametrization in JMeter for proto3 file**

(Name: KLG - Value Schema File Load Generator Config
Name Strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
Serializer: net.coru.kloadgen.serializer.ProtobufSerializer
Scema Type: PROTOBUF)

[parameterization_notworking.zip](https://github.com/corunet/kloadgen/files/8765617/parameterization_notworking.zip)

### KloadGen Version

Kloadgen-4.6

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by irodigl** [comment]
Hi @nrellanti,

Thank you for your collaboration, we will review the problem and we will inform you as soon as possible.

**Comment by irodigl** [comment]
Hi @nrellanti!

We've been investigating about that and we have detected the problem.. Currently those types are not being supported by the application, so we are going to add them. We calculate having the changes at the beginning of the next week, and I will notice you for testing it.

Thanks for the support :)

See ya!

**Comment by irodigl** [comment]
Hi @nrellanti!

We already fix the issue and uploading the code into branch [255_fix_protobuff_date_timeofday](https://github.com/corunet/kloadgen/tree/%23255_fix_protobuff_date_timeofday) Please, could you updating your solution and testing it for checking if the problem is solved?

Thank you! :)

**Comment by nrellanti** [comment]
Hi @irodigl ,
Tested and verified the date and time issue.
Thank you very much for all the help and support you have done.
