### ISSUE TITLE
[Issue]: Release all versions on github releases

### ISSUE THREAD

**Issue by NehaviTersarma** [corunet/kloadgen#259]
### What happened?

Hello team,
We using this plugin for my project in my comapny. We using it from the github releases but it is not updated. It will be very helpful for us if you release every version for us! 
Please and thankyou.

### KloadGen Version

KloadGen

### Relevant log output

```shell
No
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by irodigl** [comment]
Hi @NehaviTersarma!

We have resolved the issue and the changes are available in [master](https://github.com/corunet/kloadgen).

Thanks for the support! :)
