### ISSUE TITLE
Serializer Drop down in  Value Scehma load generator config shows empty . No values in that

### ISSUE THREAD

**Issue by ShabdaDev** [corunet/kloadgen#282]
### What happened?

Hi There ,

I installed as a jmeter library and put that (  kloadgen.jar )  in jmeter  ext/lib folder . After that while scripting i  dont see  any value in dropdown of field  Serializer.  Can you please help here ?   I am not including the test plan and schema currently because maybe it's some issue on my side but am not able to figure out what.

![image](https://user-images.githubusercontent.com/71424189/180969218-1d17aaee-eeb9-4160-b005-613bc44317a1.png)

### KloadGen Version

Kloadgen 4.12.2

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by dianaGomezGar** [comment]
Hi @ShabdaDev, 
To verify if this is a config problem we need you to add your Testplan file so we can try it.  Thank you.

**Comment by dvtoever** [comment]
I experienced exactly the same. It turned out that `org.apache.kafka:kafka-clients:3.6.1` that was included in the KLoadGen jar was also present in the `lib` directory of jmeter. This resulted in an empty Serializer dropdown. When I delete the jar from the jmeter lib dir it was working again.
