### ISSUE TITLE
Issue with running kloadgen plugin on Windows 10

### ISSUE THREAD

**Issue by Aleh-Voinau** [corunet/kloadgen#3]
This is the only plugin that I fond that declare ability to send kafka message with a header. But unfortunately it doesn't work for me. 

Details: 
1. There is an issue in Jmeter 5.1.1 while sending a kafka message.  I used Example-Test-Plan.jmx from the git folder.
Log from jmeter:
```
020-03-31 20:21:19,802 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer Properties'.
java.lang.NullPointerException: null
at java.util.Hashtable.put(Hashtable.java:460) ~[?:1.8.0_241]
at net.coru.kloadgen.sampler.ConfluentKafkaSampler.setupTest(ConfluentKafkaSampler.java:136) ~[kloadgen-1.0.jar:?]
at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:196) ~[ApacheJMeter_java.jar:5.1.1 r1855137]
at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) ~[ApacheJMeter_core.jar:5.1.1 r1855137].....
```
![image](https://user-images.githubusercontent.com/62956725/78157970-583c4180-7449-11ea-9f1f-861049eb684c.png)

2. Issue during " mvn clean install" to create a jar file.
I had to add the lines below to pom.xml file, because  confluent.io files are not available by default path during compiling. 

```
 <repositories>
    <repository>
     <id>confluent</id>
     <url>http://packages.confluent.io/maven/</url>
   </repository>
  </repositories>
```

![image](https://user-images.githubusercontent.com/62956725/78157910-435fae00-7449-11ea-8d54-fe00c0d1d7f7.png)

The issue with building a jar file is still exists for me on Windows if I use the provided Setting.xml file.
What I done:
I've put the setting file that you sent me to my \.m2\ folder; there is no effect, it looks that it doesn't work for windows. 
I've put it to maven home directory, the logs while building the project were changed, but in the end I have the same issue.

**Comment by kszosze** [comment]
Hi Aleh,
Thanks for the feedback. 
We are gonna take a look into it.
Will anwser as soon we know something.
Cheers
