### ISSUE TITLE
[Issue]: PlainTextLoadGenerator throws NotImplementedExceptions

### ISSUE THREAD

**Issue by Kricket** [corunet/kloadgen#306]
### What happened?

I've been trying to use KLoadGen to send the value of a variable as the content of a Kafka message. (Reading lines from a data file and sending them...)

Unfortunately, it appears that the [PlainTextLoadGenerator](https://github.com/corunet/kloadgen/blob/c47484984d0dd504850ccf7817b55a51230bb328/src/main/java/net/coru/kloadgen/loadgen/impl/PlainTextLoadGenerator.java#L27) throws a `NotImplementedException` in each of its `setUpGenerator` methods.

I compiled a custom version where these lines are commented, and it runs without a problem.

Are these exceptions necessary? Am I missing something, or is there no problem with simply removing them?

### KloadGen Version

5.1.2

**Comment by dianaGomezGar** [comment]
Hi Kricket! 
Thank you for your report, we will review this issue and answer you as soon as possible.

**Comment by dianaGomezGar** [comment]
Hi again, 
We had that exceptions to control some behaviours, but I made some changes in the associated PR to fix it. Can you check if it resolves your problem?

**Comment by Kricket** [comment]
Hello, yes that solves the problem, thanks!
