### ISSUE TITLE
[Issue]: Can we add provision for custom kafka serializers and deserializers

### ISSUE THREAD

**Issue by LeenaMarathe** [corunet/kloadgen#308]
### What happened?

Hi,

Can we add a provision for Customized avro Serializers and Deserializers. Currently I am facing an issue because my service is using a customized serializers and hence I am not able to post a message on a particular topic. Is it possible to add custom serializer so that message that I am posting can be serialized into appropriate avro format and posted successfully on topic.
Note - Due to compliance issues, I won't be able to share schema and jmx plan.

### KloadGen Version

5.1.2

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by dianaGomezGar** [comment]
Hi @LeenaMarathe,

Thank you for your collaboration. We are going to take a look and we answer you as soon as possible.

**Comment by dianaGomezGar** [comment]
Hi @LeenaMarathe,

I just made some changes. You can add your custom serializer to the **/lib/ext** JMeter folder and test it with the changes in the associated branch.  

Please, let me know if this works for you.

**Comment by dianaGomezGar** [comment]
Hello @LeenaMarathe,

Any news about this?

**Comment by dianaGomezGar** [comment]
I'm going to close due to inactivity. If you have any question you can open a new Issue or reopen this one.
