### ISSUE TITLE
AVSC file for the example jmx

### ISSUE THREAD

**Issue by quyeny2k** [corunet/kloadgen#36]
Can you post the avsc file for the example?  Thanks.

**Comment by kszosze** [comment]
Hi there,
we are publish an example quite soon.
Next release is coming!
Cheers!

**Comment by kszosze** [comment]
Hi there,
New version just pop out the oven.
As I said, I added an AVSC file as an example. It's not the we use in the example Jmx, since this example was made to run against a Schema Registry, but that will let you play around a bit.
That suits you?
Cheers
