### ISSUE TITLE
Update guava to version 24.1.1 to solve medium vulnerability

### ISSUE THREAD

**Issue by bernalvarela** [corunet/kloadgen#38]
The guava version used in project has a solved vulnerability in the version 24.1.1 it should be a good practice to update the library to solve this vulnerability.

https://github.com/corunet/kloadgen/network/alert/pom.xml/com.google.guava:guava/open

**Comment by kszosze** [comment]
Thanks,
It will be upgrade to the latest one.
Cheers!!
