### ISSUE TITLE
Error opening file Example-Test-Plan.jmx

### ISSUE THREAD

**Issue by erobertolima121** [corunet/kloadgen#43]
When opening the Example-Test-Plan.jmx file, I am getting the following error:

io/confluent/kafka/schemaregistry/client/rest/exceptions/RestClientException

I performed the settings mentioned, clean and install, and added the .jar in the lib folder.

Can anyone help?

![image](https://user-images.githubusercontent.com/40573811/86961510-b73fdf80-c137-11ea-99e9-ca8e2d48ed4a.png)

**Comment by codigoFuentes** [comment]
Hello Roberto. Can you check that there is only one kloadgen-1.5.1.jar in  /lib/ext folder?

**Comment by erobertolima121** [comment]
> Hello Roberto. Can you check that there is only one kloadgen-2.0.0.jar in /lib/ext folder?

Hi @codigoFuentes. Yes, I only have a kloadgen-2.0.0.jar / lib / ext folder

Any more suggestions? Thank's.

![image](https://user-images.githubusercontent.com/40573811/87040412-0719b780-c1c7-11ea-8d36-7a8b82f685d0.png)

**Comment by codigoFuentes** [comment]
Hello Roberto. We need to update the Example-Test-Plan.jmx file because it is causing problems with schema registry. With your own test plan it should work correctly.

**Comment by erobertolima121** [comment]
> Hello Roberto. We need to update the Example-Test-Plan.jmx file because it is causing problems with schema registry. With your own test plan it should work correctly.

To generate the .jar just perform clean/install, I verified that the project has errors, can I generate the .jar even with them present?

Could this not be the initial cause of the problem?

![image](https://user-images.githubusercontent.com/40573811/87101035-5c37e680-c224-11ea-8885-141420391ffc.png)

**Comment by erobertolima121** [comment]
> Hello Roberto. We need to update the Example-Test-Plan.jmx file because it is causing problems with schema registry. With your own test plan it should work correctly.

In an attempt to create my own test plan, I get an error when trying to add the configuration element "Kafka Load Generator Config"

2020-07-09 20:26:53,081 WARN o.a.j.g.u.MenuFactory: Configuration error, probably corrupt or missing third party library(jar)? Could not create class: net.coru.kloadgen.config.schemaregistry.SchemaRegistryConfigElement.
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at net.coru.kloadgen.config.schemaregistry.DefaultPropertiesHelper.<clinit>(DefaultPropertiesHelper.java:20) ~[kloadgen-2.0.0.jar:?]
	at net.coru.kloadgen.config.schemaregistry.SchemaRegistryConfigElementBeanInfo.<init>(SchemaRegistryConfigElementBeanInfo.java:39)

Thank you for your help.

**Comment by kszosze** [comment]
Hi Roberto,
there is a mistake in the Readme file. You should use the kloadgen-plugin-2.0.0.jar instead. 
Can you please, replace the one you are using with this one (is in the same target folder) and try again.
Those errors you said looks like classpath problems in you IDE.. intellij?  some times you need you invalidate cache and restart.
Build was success, so nothing wrong happen.
Cheers!!

**Comment by erobertolima121** [comment]
> Hi Roberto,
> there is a mistake in the Readme file. You should use the kloadgen-plugin-2.0.0.jar instead.
> Can you please, replace the one you are using with this one (is in the same target folder) and try again.
> Those errors you said looks like classpath problems in you IDE.. intellij? some times you need you invalidate cache and restart.
> Build was success, so nothing wrong happen.
> Cheers!!

This suggestion worked! The plugin was added, presented in Jmeter, and the sample .jmx was read and worked perfectly.

@kszosze @codigoFuentes I appreciate the help and support.

Thanks a lot!!
