### ISSUE TITLE
Failed retrieve schema properties

### ISSUE THREAD

**Issue by erobertolima121** [corunet/kloadgen#44]
When I click on the option "Test Registry" I am getting the error below, has anyone experienced this problem, any tips to help me?

Failed retrieve schema properties : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Thanks!

**Comment by kszosze** [comment]
Hi E Roberto,
looks like you are using an authenticated schema registry. 
In order to connect, you need to introduce the properties for that in the table below the Schema Registry URL.
You should see a list of properties with the Bearer data or the Certificate.
Do you know what kind of security is using your schema registry?
Cheers!!

**Comment by erobertolima121** [comment]
> Hi E Roberto,
> looks like you are using an authenticated schema registry.
> In order to connect, you need to introduce the properties for that in the table below the Schema Registry URL.
> You should see a list of properties with the Bearer data or the Certificate.
> Do you know what kind of security is using your schema registry?
> Cheers!!

Hi, @kszosze,

I'm using SSL (with keystore and truststore keys), I have the jks files and the password to connect, but I don't know how to configure them in this case.

Thanks for the prompt help.

**Comment by erobertolima121** [comment]
> > Hi E Roberto,
> > looks like you are using an authenticated schema registry.
> > In order to connect, you need to introduce the properties for that in the table below the Schema Registry URL.
> > You should see a list of properties with the Bearer data or the Certificate.
> > Do you know what kind of security is using your schema registry?
> > Cheers!!
> 
> Hi, @kszosze,
> 
> I'm using SSL (with keystore and truststore keys), I have the jks files and the password to connect, but I don't know how to configure them in this case.
> 
> Thanks for the prompt help.

Hi @kszosze ,

Do you have an example of this configuration?

Thanks!

**Comment by kszosze** [comment]
Hi @erobertolima121 
Sure I´ll provide an example. I have the task to increase the examples test plans.
Just last days where a bit busy right here. I´ll do it asap
Cheers.

**Comment by kszosze** [comment]
HI @erobertolima121 

after rereading the conversation (sorry this week was hard) we only support the 2 types of security actually implement Confluent Schema Registry, means Basic and token Bearer. I added couple of screen shots with examples. Certificates and jks files are used typically to connect to the kafka brokers. That configuration is done in the Java Request configuration section
Basic auth
![Screenshot 2020-07-16 at 19 03 49](https://user-images.githubusercontent.com/302714/87701202-dd98f700-c797-11ea-88f8-74c92a4faee9.png)
Bearer Token Auth
![Screenshot 2020-07-16 at 19 06 25](https://user-images.githubusercontent.com/302714/87701213-e1c51480-c797-11ea-9ed2-f985f65d5eb6.png)

Those ones solve your problem?

**Comment by kszosze** [comment]
Hi @erobertolima121 ,

any joy with that issue?

Cheers

**Comment by erobertolima121** [comment]
Hi @kszosze,

Sorry for the absence, there were some emergencies and I had to change the focus.

Tomorrow, I will hold a meeting with the area responsible for Kafka and the Schema Registry to clarify the possible way of connecting.

I will return to bring news.

Thank you for your usual attention.

**Comment by kszosze** [comment]
hi @erobertolima121 

no worries, if we can assists you in something, we have experience with Kafka and Big Data processing.

Cheers!!

**Comment by erobertolima121** [comment]
Hi @kszosze ,

I confirmed and to access the schema registry and read all registered AVROS I will need to authenticate using some type of certificate.

Can the plugin in the schema registry settings handle this situation?

**Comment by kszosze** [comment]
Hi @erobertolima121,
we will take a look into it.
Are you able to provide an example dockerfile with your deployment?
Cheers!!

**Comment by kszosze** [comment]
Hi @erobertolima121 ,
Just a thought in the meantime we are preparing a testing environment, in java rest calls typically you add the certificate in the keystore in for the jvm. Like those answers here .. https://stackoverflow.com/questions/875467/java-client-certificates-over-https-ssl.
Can you try if that approach work for you? Just need to add your server certificates with the keytool in the the keystore and try with the normal access to the Schema Registry, since looks you don't have a proper username/password (right?) probably will be easy.
In the meantime we will investigate a way to do it.
Regards!

**Comment by kszosze** [comment]
Hi @erobertolima121,
Still on it... Had you the chance the try my list suggestion?
Cheers!!

**Comment by kszosze** [comment]
Close due not feedback/answer
