### ISSUE TITLE
"Not an array" AvroRuntimeException while loading subject in kafkaloadgenerator config in JMeter

### ISSUE THREAD

**Issue by Meenu1242** [corunet/kloadgen#47]
On clicking load subject in Kafka Load generator config, getting below error.

Org.apache.avro.AvroRuntimeException: Not an array:["null", {"type" :"array", "items" :{"type" :"record", "name" :"UserRule", "namespace" :"com.user.details","fields":[{"name":"code", "type" :"int"}, {"name" :"override", "type" :{"type" :"string", "avro.java.string":"string"}}]}}]

Below is the avro schema.
{
"type":"record",
"name":"User",
"namespace":"com.user.details",
"fields":[{
"name":"username",
"type":"string"
},
{"name":"blocks",
"type":["null", {
"type" :"array",
"items" :{
"type" :"record", 
"name" :"UserRule", 
"fields" :[{
"name" :"code", 
"type" :"int"}, 
{
"name" :"override", 
"type" :["null", "string"], 
"default":null
}]}}], 
"default":null
}]} 

Could you please look into why the error is coming up?

**Comment by kszosze** [comment]
HI @Meenu1242 ,

I´ll take a look at it, asap.
Can you please add the full stack trace with the error?

Thanks for the feedback!

**Comment by kszosze** [comment]
Hi @Meenu1242,

I have a branch with a solution, Do you mind try it?
I think it will solve your problem.
Cheers!

**Comment by Meenu1242** [comment]
Thanks a lot. The issue is resolved. Appreciate your quick response!
