### ISSUE TITLE
Duplicate array item issue in Kafka Load generator

### ISSUE THREAD

**Issue by Meenu1242** [corunet/kloadgen#49]
In Kafka Load Generator config option in JMeter, when we hard code one value for an array field, the load generator is duplicating the value multiple times. Is there a way to restrict the number random generator to generate values only once in this case? 

Example: There is an array as address[] and 2 fields under it as address[].addressId and address[].city and I have set addressId as 1 and city as abc. Field Length for both of them is set to 0. However when I run the script, it shows address multiple times as below. Due to this the functionality is failing as duplicate addressId is not allowed in my application. 

"address":[{
"addressId" :1,
"city":abc},
{"addressId":1,
"city" :abc},
{"addressId" :1,
"city":abc}]

**Comment by codigoFuentes** [comment]
Hi Meenu1242.

In your case, you should insert the number of times you want to execute in the "Field Name" section in the middle of the square brackets, such as "address [1] .addressId". This is better explained in readme file, please take a look at it and if you have any questions, we will help you with whatever.

Best regards.

**Comment by Meenu1242** [comment]
Thanks for the clarification. Issue is resolved.
