### ISSUE TITLE
Duplicate values generated in random tool

### ISSUE THREAD

**Issue by Meenu1242** [corunet/kloadgen#50]
Hi Team,

When using the Kafka Load Generator config, I have an integer field Customer Id for which I haven't set a definitive list and would like random number to be generated. 

However, I see same number getting duplicated 3 out of 6 times. Is there a way to ensure the duplicates aren't generated or atleast reduce the frequency? I checked the documentation provided but couldn't find any solution in this regard. 

Note: I am setting up load generator for testing a kafka publisher. So raising questions as and when I encounter. Appreciate your quick response/clarification so far.

**Comment by codigoFuentes** [comment]
Can you show me the test you are using?

**Comment by Meenu1242** [comment]
I work in a secure network. So unfortunately, will not be able to show the test

**Comment by codigoFuentes** [comment]
Ok. The Field Value List in Costumer Id is empty??

**Comment by Meenu1242** [comment]
Yeah. That's right

**Comment by codigoFuentes** [comment]
As an implementation detail, when no size is indicated in the Field Length, random numbers between zero and nine will be generated. This behavior is like this In order to avoid generating large numbers. This clarification is something that we will add in the documentation. I hope this helps.

**Comment by Meenu1242** [comment]
OK. But if I specify value in Field length , it is not allowing me to edit any other field and is not considering the field length input as well. Error is seen in Jmeter console logs. 

Format of input in Jmeter Kafka Load generator config:
Field Name ¦ Field type ¦ Field length ¦ Field value ¦
CustomerId ¦ String ¦ 5 ¦ [] 

Error displayed:
Org.apache.jorphan.util.JmeterError: Cant find method net.coru.kloadgen.midel.FieldValueMapping#setValueLength(java.lang.string)
at org.apache.jorphan.reflect.Functor.doInvoke(Functor.java.256) ~[jorphan.jar:5.3]
at org.apache.jorphan.reflect.Functor.invoke(Functor.java.322) ~[jorphan.jar:5.3]
at org.apache.jorphan.gui.objectTableModel.setValueAt(ObjectTableModel.java:224) ~[jorphan.jar:5.3]
at javax.swing.JTable.setValueAt(Unknown Source) ~[? 1.8.0_251]
at javax.swing.JTable.editingStopped(Unknown Source) ~[? 1.8.0_251]
at javax.swing.AbstractCellEditor.fireEditingStopped (Unknown Source) ~[? 1.8.0_251]

**Comment by codigoFuentes** [comment]
In order to reproduce the error, can you copy the entire error trace to me? And can you show me what you have in lib/ext folder?

**Comment by Meenu1242** [comment]
Unfortunately I do not have an option to share the details as it is in restricted network. However, as a workaround, I was able to create an input csv with a definitive set of values and run the test against that. With this, the number of duplicates were reduced and data was picked up sequentially from the csv file.

**Comment by kszosze** [comment]
Hi @Meenu1242,
it's great you come up with a solution. But reading your last comment, you realize that you can generate a sequence of numbers just setting the type as seq right? It will generate a sequence starting from 1, or the value you put into the Field Value List.
Or you were requesting generate an unique number sequence, I mean generate a set of numbers without no one repeated.
Cheers!

**Comment by kszosze** [comment]
Closing this issue due inactivity.
