### ISSUE TITLE
Publish to Kafka using partitionkey

### ISSUE THREAD

**Issue by Ramprasad2505** [corunet/kloadgen#51]
Hi,

Is there a way to send partitionkey along with topic name and message to Kafka through this plugin?

**Comment by kszosze** [comment]
Hi @Ramprasad2505 ,
For now it's not possible. Generated key if Flag is True, will be an UUID. But it's in our roadmap to add for the next release.
Do you require such feature?
Cheers!!

**Comment by kszosze** [comment]
Hi @Ramprasad2505,
here we had prepared a candidate to Message Key Management. 
If you wanna try the branch to see if fits your needs ..
Cheers!!
