### ISSUE TITLE
schema is not able to determine  the array having optional array

### ISSUE THREAD

**Issue by hariprasad5a0** [corunet/kloadgen#54]
2020-09-08 23:26:19,331 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Java Request'.
org.apache.avro.AvroRuntimeException: Not an array: ["null",{"type":"array","items":{"type":"record","name":"PCC_Array_Details","namespace":"com.bell.pec.out.data","fields":[{"name":"LOB_PCC","type":{"type":"array","items":{"type":"record","name":"LOB_Details_PCC","fields":[{"name":"LOB_Code","type":"int"},{"name":"Billed_from","type":"int"},{"name":"Nbr_Of_Days","type":"int"},{"name":"LOB_PCC_BLDT1","type":"float"},{"name":"LOB_PCC_BLDT2","type":"float"},{"name":"LOB_PCC_BLDT3","type":"float"}]}}},{"name":"Total","type":{"type":"record","name":"Total_PCC_Details","fields":[{"name":"PCC_BLDT1","type":"float"},{"name":"PCC_BLDT2","type":"float"},{"name":"PCC_BLDT3","type":"float"}]}}]}}]
	at org.apache.avro.Schema.getElementType(Schema.java:356) ~[kloadgen-plugin-2.0.1.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.next(AvroSchemaProcessor.java:76) ~[kloadgen-2.0.1.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.nextMessage(AvroLoadGenerator.java:60) ~[kloadgen-2.0.1.jar:?]
	at net.coru.kloadgen.sampler.ConfluentKafkaSampler.runTest(ConfluentKafkaSampler.java:253) ~[kloadgen-2.0.1.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by kszosze** [comment]
Hi @hariprasad5a0 ,
Can you provide an example AVRO file with this case so we can test it?
Cheers!

**Comment by kszosze** [comment]
HI,
I prepare a branch with a possible fix. 
Do you mind test it if it works for you?

Cheers!!

**Comment by hariprasad5a0** [comment]
hi @kszosze 

now its working fine but getting below exception.

2020-09-09 10:48:53,270 ERROR n.c.k.s.ConfluentKafkaSampler: Failed to send message
org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema: {"type":"record","name":"PredictionEvent_output","namespace":"com.bell.pec.out.data","doc":"Avro schema representing PEC realtime prediction event output data ","fields":[{"name":"OrderMAX_Order_ID","type":"string"},{"name":"Input_Timestamp","type":"long"},{"name":"Bill_Date","type":{"type":"record","name":"Bill_Date_Details","fields":[{"name":"BLDT1","type":"int","logicalType":"date"},{"name":"BLDT2","type":"int","logicalType":"date"},{"name":"BLDT3","type":"int","logicalType":"date"}]}},{"name":"Upcoming_Bills","type":{"type":"record","name":"upcoming_bill_details","fields":[{"name":"Total_MRC_Adjustment","type":"float"},{"name":"LOB_Upcoming_Bills","type":{"type":"array","items":{"type":"record","name":"LOB_details_upcoming_bills","fields":[{"name":"LOB_Code","type":"int"},{"name":"LOB_Effective_Date","type":"int","logicalType":"date"},{"name":"LOB_Invoice_Month","type":"int"},{"name":"LOB_Total_BLDT1","type":"float"},{"name":"LOB_Total_BLDT2","type":"float"},{"name":"LOB_Total_BLDT3","type":"float"}]}}},{"name":"Service_Rate_Adj","type":["null",{"type":"array","items":{"type":"record","name":"Service_Rate_Adj_details","fields":[{"name":"LOB_Code","type":"int"},{"name":"SRAdj_Effective_Date","type":"int","logicalType":"date"},{"name":"SR_Adj_BLDT1","type":"float"},{"name":"SR_Adj_BLDT2","type":"float"},{"name":"SR_Adj_BLDT3","type":"float"}]}}]},{"name":"MRC_Adjustment","type":{"type":"record","name":"MRC_Adjustment_Details","fields":[{"name":"Adjustment_BLDT1","type":"float"},{"name":"Adjustment_BLDT2","type":"float"},{"name":"Adjustment_BLDT3","type":"float"}]}},{"name":"Partial_Charges_And_Credits_UB","type":{"type":"record","name":"PCC_Details","fields":[{"name":"PCC_BLDT1","type":"float"},{"name":"PCC_BLDT2","type":"float"},{"name":"PCC_BLDT3","type":"float"}]}},{"name":"One_Time_Fees","type":{"type":"record","name":"OTF_Details","fields":[{"name":"OTF_BLDT1","type":"float"},{"name":"OTF_BLDT2","type":"float"},{"name":"OTF_BLDT3","type":"float"}]}},{"name":"Total","type":{"type":"record","name":"Total_Details","fields":[{"name":"Total_BLDT1","type":"float"},{"name":"Total_BLDT2","type":"float"},{"name":"Total_BLDT3","type":"float"}]}}]}},{"name":"Partial_Charges_And_Credits","type":["null",{"type":"array","items":{"type":"record","name":"PCC_Array_Details","fields":[{"name":"LOB_PCC","type":{"type":"array","items":{"type":"record","name":"LOB_Details_PCC","fields":[{"name":"LOB_Code","type":"int"},{"name":"Billed_from","type":"int"},{"name":"Nbr_Of_Days","type":"int"},{"name":"LOB_PCC_BLDT1","type":"float"},{"name":"LOB_PCC_BLDT2","type":"float"},{"name":"LOB_PCC_BLDT3","type":"float"}]}}},{"name":"Total","type":{"type":"record","name":"Total_PCC_Details","fields":[{"name":"PCC_BLDT1","type":"float"},{"name":"PCC_BLDT2","type":"float"},{"name":"PCC_BLDT3","type":"float"}]}}]}}]}]}
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject not found. io.confluent.rest.exceptions.RestNotFoundException: Subject not found.
io.confluent.rest.exceptions.RestNotFoundException: Subject not found.

**Comment by kszosze** [comment]
Hi @hariprasad5a0,
That usually happen when the subject from the AVRO schema differs form the ones the Schema Registry has.
I saw that couple of times when pre saved test plans try to send data and the subject change its name in the Schema Registry.
From the stack trace you shared I cannot see the subject name. Can you please provide a JMX test plan? If you cannot because privacy restrictions, Can you please reproduce that error with a shareable file?
Apart of that, can you please describe which components are you using? or just some screenshots.
Cheers,

**Comment by hariprasad5a0** [comment]
hi @kszosze 

above issue is resolved now but we are getting the below error. and attached the 

org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Float

![image](https://user-images.githubusercontent.com/70971663/92594740-dafedd80-f2c0-11ea-8e3a-b407789909a2.png)

**Comment by kszosze** [comment]
Hi @hariprasad5a0,
usually we prefer one issue ticket by problem, but here I already have the solution.
As you could read in the documentation we don't support Float type.. But I'll push a fix so you can test it.
I'll reuse the previous branch.
Waiting for feedback.
Cheers

**Comment by hariprasad5a0** [comment]
hi @kszosze 

Now it is working fine.
