### ISSUE TITLE
Schema Registry URL is behind a proxy

### ISSUE THREAD

**Issue by vcbkarthi** [corunet/kloadgen#56]
i can access the schema registry URL in browser and its behind a proxy , need to know how do i use that in schema registry config element

**Comment by vcbkarthi** [comment]
when i use the schema registry url in the config it says connection time out

**Comment by kszosze** [comment]
Hi @vcbkarthi ,
that's odd. We never tried with a proxy in between, but we are gonna investigate it.
Cheers!!

**Comment by vcbkarthi** [comment]
Running jmeter with proxy has solved the problem . But landed in another
issue . Which I believe is network issue.

Thanks for emailing me

**Comment by kszosze** [comment]
HI @vcbkarthi,
I´m glad you could do it.
Thanks for the feedback!
