### ISSUE TITLE
Parametrize the Kafka Load Generator Config

### ISSUE THREAD

**Issue by vcbkarthi** [corunet/kloadgen#57]
Hi is it possible to parameterize the Kafka Load Generator Config field list values ?

my scenarios is message.key.value have to be unique for every 4 consecutive messages that we post to Kafka

1) i need to generate a unique value for the message.key.value
2) parameterize the Kafka Load Generator Config field list values

will normal CSV data config will work here to pass the messages ( this is to mimic a scenario and need to send specific messages and not random generated ones )

let me know how do i achieve this 

example 

message Key value : 123456 then is send four messages taken from CSV and send to kafka topic and then change the message key value for the next iteration .

**Comment by kszosze** [comment]
Hi @vcbkarthi,
in order tu solve your problem, there are couple of ways to do it; without see your test plan.
We support a "seq" type which is like a workaround to generate a sequences of numbers, you can define the starting value in the Field Values List.
We also support JMeter variable replacement, just  add the jmeter variable name in the Field Values List like a normal JMeter  component "${ name of the variable }", so you can read your CVS and add the column there.
In botch approaches you need to define a loop of 4 messages to send.
Please tell us if that works for you.

**Comment by vcbkarthi** [comment]
i define a loop just for the Kafka Load Generator Config correct ?

**Comment by kszosze** [comment]
Well ideally you define the properties in the Thread element or in the Test Plan Element there are some values where you can define how many iterations you will run.

**Comment by kszosze** [comment]
Close due not feedback/answer
