### ISSUE TITLE
Custom properties

### ISSUE THREAD

**Issue by Kara4un** [corunet/kloadgen#58]
Hi!

In readme we can find

```
Above properties are added by default in sampler as those are more significant in terms of performance in most of the cases. But you can add other non listed kafka properties with prefix "_".

For example to enable SSL properties you can add below properties

_ssl.key.password
_ssl.keystore.location
```

I am trying to add 
_ssl.enabled.protocols = [TLSv1.2]

and some other props to Kafka Producer Properties below default props. But it seems that it's not working. After each start jmeter deletes this custom props, and I see only defaults in log output.

Is this feature work properly, or I do something wrong?

Apache jmeter 5.2.1
KLoadGen 2.1.2

**Comment by kszosze** [comment]
Hi @Kara4un,
we are gonna take a look into it.
Is possible for you to share the test plan (or a similar one) so we can try to reproduce the issue?
Cheers!!

**Comment by Kara4un** [comment]
Thx a lot. 
This is jmeter jmx for this test plan

https://drive.google.com/file/d/1qI1ntToheCCgGMXIbLezgfYsr00b3JB2/view?usp=drivesdk

**Comment by kszosze** [comment]
Hi @Kara4un,
issue is most a "way how jmeter works" It looks like it reload the default properties set and remove whatever is not there. We are extending a JMeter component for the Sampler instead to use our own (change that is in the roadmap, somewhere).
For now, please send me the properties you will need and I'm happy to add them asap.
Cheers!!

**Comment by Kara4un** [comment]
Hi @kszosze 
This is the list of prop, that i need to add in my config list

client.id
key.serializer
security.providers
ssl.enabled.protocols
ssl.endpoint.identification.algorithm
ssl.enabled.protocols
ssl.keymanager.algorithm
ssl.keymanager.algorithm
ssl.protocol
ssl.keystore.type
ssl.provider

It would help me a lot, if you can add them

**Comment by kszosze** [comment]
Hi @Kara4un 
I'll add those but keep in mind that we provide 3 samplers, Confluent, Generic and KafkaSampler (our Own Custom one), that meand the key.serializer is only configurable in the GenericKafka, since Confluent is using confluent.io ones and KafkaSampler is using the StringSerializer for keys and one custom simple implementation for values. You still need that property added? in which sampler?
Regarding the others I see no problem, but leave them empty, you mean send them empty, with no value or not send them at all. (usually empty means set a default value what I'll use as not send them)
Regards

**Comment by Kara4un** [comment]
Hi!

@kszosze I got an idea with serialization. I think we can work without this property.

Yeah, I mean, send them empty with no value. Because due to our authorization mechanism on kafka, we got an "ssl error" when producers ssl.endpoint.identification.algorithm has value differ from empty string. The default value of this prop is "https" and it is not working for us.

**Comment by kszosze** [comment]
Hi @Kara4un,
I have a branch with those new properties. Can you please if that works for you?

Regards

**Comment by Kara4un** [comment]
Hi @kszosze 

Yeah, i will try it today

**Comment by Kara4un** [comment]
Hi again @kszosze 

It near perfect now, but I have one important addition

It seems, that we should remove 
defaultParameters.addArgument(ProducerConfig.SECURITY_PROVIDERS_CONFIG, "");
defaultParameters.addArgument(SslConfigs.SSL_PROVIDER_CONFIG, "");

From config list. The reason is that if they are absent in config, kafka client pass default JVM provider classes and it's not working if they are empty.

The rest of the list are fit my goals perfectly, thank you very much!

**Comment by kszosze** [comment]
Hi @Kara4un,
I can remove them if no value comes, That will suit to your case I guess.
Cheers!

**Comment by Kara4un** [comment]
Hi! @kszosze 

Yes it seems perfect. Thank you!

**Comment by kszosze** [comment]
Hi @Kara4un,
Can you confirm this branch solve all ?
So I can merge it.
Cheers!
