### ISSUE TITLE
Limiting the size of a string-array

### ISSUE THREAD

**Issue by nitya122008** [corunet/kloadgen#64]
I have a weird schema with an array of objects
Something like this:
{
	"uuid": "d7fa5207-3ba5-4517-8d5a-256066d26e88",
	"type": "whatever",
	"data": [{
		"attribute": "name",
		"valueList": ["John"],
		"operator": "match"
	}]
}

When i use the plugin as in the below screenshot:
![image](https://user-images.githubusercontent.com/52054951/98036813-a4d56a00-1de8-11eb-8744-950e42b46050.png)

a) I am unable to limit the number of values in the array even if i set the field-length = 1. The resulting message is 
{
	"uuid": "365b57ad-d9e6-44a9-af57-1112b6b1a822",
	"type": "whatever",
	"data": [{
		"attribute": "name",
		"valueList": ["John", "John", "John"],
		"operator": "match"
	}]
}
"John" gets added at least thrice (random sizes in the list). Is there a way to limit the number of entries in the array?

b) is there a way to add multiple objects into the above list with specific data. I understand keeping data[2] would give me 2 items in the list. But i want a way to be able to control the data in the "attribute" and "valueList" fields. For example:
if I put values as "Name", "LastName" for attribute and "John", "Smith" in valueList, is there a way to ensure that the resulting message looks like this:

{
	"uuid": "365b57ad-d9e6-44a9-af57-1112b6b1a822",
	"type": "whatever",
	"data": [{
			"attribute": "name",
			"valueList": ["John"],
			"operator": "match"
		},
		{
			"attribute": "last_name",
			"valueList": ["Smith"],
			"operator": "match"
		}
	]
}

instead of everything being randomly picked and mixed and matched in the request ?

Can you please help?

**Comment by kszosze** [comment]
HI @nitya122008 ,
we will take a look into this and will offer soon a solution.
Cheers!

**Comment by nitya122008** [comment]
Hi @kszosze ,
Do you think you might be able to help with item number a) on priority if you get a chance please?

**Comment by kszosze** [comment]
Hi @nitya122008,
apologizes for the delay, had been a really busy week in our main task. But we are gonna be able to have something before weekend.
Cheers!!!

**Comment by codigoFuentes** [comment]
Hi @nitya122008 
Apologies for the delay, we have a pull request(add array extractor changes #67) that we think may solve your issues. These changes will allow you limit the number of values in the array and add multiple objects into a list with specific data.

**Comment by nitya122008** [comment]
I took this code and i keep getting "Topic cannot be null" error. I have the topic available and I have set it in the kafka.topic.name attribute as well. I am able to manually place messages into that topic but through Jmeter, i keep getting the error.

![image](https://user-images.githubusercontent.com/52054951/98973425-b94ced00-24e1-11eb-830c-5c6be442dcce.png)

Would you know what i might be doing wrong here?

**Comment by codigoFuentes** [comment]
Can you attach and example AVRO and an example Test Plan in order to be able to reproduce the error?

**Comment by nitya122008** [comment]
Sample Avro : 

```
{
	"name": "SampleAvro",
	"namespace": "a.sample",
	"type": "record",
	"fields": [{
		"name": "uuid",
		"type": "string"
	}, {
		"name": "type",
		"type": {
			"name": "QueryType",
			"type": "enum",
			"symbols": ["size", "estimate"]
		}
	}, {
		"name": "data",
		"type": {
			"type": "array",
			"items": {
				"name": "Sample",
				"type": "record",
				"fields": [{
					"name": "attribute",
					"type": "string"
				}, {
					"name": "valueList",
					"type": {
						"type": "array",
						"items": "string"
					}
				}, {
					"name": "operator",
					"type": {
						"name": "Operator",
						"type": "enum",
						"symbols": ["match", "greater"]
					}
				}]
			}
		},
		"default": []
	}]
}
```

**Comment by nitya122008** [comment]
Load Generator Config:
![image](https://user-images.githubusercontent.com/52054951/98977816-0aabab00-24e7-11eb-8ec8-344c956df2ea.png)

**Comment by nitya122008** [comment]
I see that the error occurs in ConfluentKafkaSampler line# 85
` props.put(ENABLE_AUTO_SCHEMA_REGISTRATION_CONFIG, context.getParameter(ENABLE_AUTO_SCHEMA_REGISTRATION_CONFIG));`

2020-11-12 13:23:19,908 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Java Request'.
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
	at java.util.Properties.put(Properties.java:1331) ~[?:?]
	at net.coru.kloadgen.sampler.ConfluentKafkaSampler.setupTest(ConfluentKafkaSampler.java:85) ~[kloadgen-plugin-2.1.4.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:195) ~[ApacheJMeter_java.jar:5.2]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) ~[ApacheJMeter_core.jar:5.2]

I tried adding "auto.register.schemas" in the request, but jmeter didnt allow me to add the new parameter in the Request.

**Comment by nitya122008** [comment]
Would you be able to please guide me with this?

**Comment by codigoFuentes** [comment]
Can you test this new arrangement and give me your feedback?

**Comment by nitya122008** [comment]
The above errors are after using the new code that you gave me.

**Comment by codigoFuentes** [comment]
Sorry.I have just added changes so can you please test it now?

**Comment by nitya122008** [comment]
hi @codigoFuentes, 

I am now able to limit the number of items in the valueList[]. For example 
data[1].valueList[2] generated the values like this : 
{"uuid":"37dc30ff-195f-4467-89f2-fb9d95d6a682","type":"size","data":[{"attribute":"rolling_date","valueList":["200","100"],"operator":"greater"}]}
![image](https://user-images.githubusercontent.com/52054951/99453593-2a7e0d00-28f3-11eb-8b7a-9583de214c26.png)

But the values still get mix and matched like this too:
{"uuid":"abbc7ac3-e8ce-4e86-bfc3-e3657a6b6bd9","type":"size","data":[{"attribute":"rolling_date","valueList":**["200","200"],**"operator":"greater"}]} (the same value getting added to the array)

Also, If i do data[2].valueList[2] as in the below screenshot:

![image](https://user-images.githubusercontent.com/52054951/99453348-cce9c080-28f2-11eb-943d-2cab89c15303.png)

the values are getting completely mismatched like below:
{"uuid":"6902e76f-c43a-4d8b-8c60-d21c87bc5798","type":"size","data":[{"attribute":"country_code","valueList":["us","100"],"operator":"match"},{"attribute":"rolling_date","valueList":["200","200"],"operator":"greater"}]}

is there any way to generate the record like this instead:
{"uuid":"943f39b0-cabe-4331-97a2-80d120d945a4","type":"size","data":[{"attribute":"rolling_date","valueList":["200","100"],"operator":"greater"},{"attribute":"country_code","valueList":["us","mx"],"operator":"match"}]}

**Comment by codigoFuentes** [comment]
The values that you enter in the valueList [] are used as a reference set just like the enumerated types. In your case you should generate the values outside and pass them as a variable.
