### ISSUE TITLE
no messages are sent to kafka

### ISSUE THREAD

**Issue by vitalee78** [corunet/kloadgen#68]
Hello!
trying to send a message to kafka - key and value. (see message_for_Kafka.json)
but in kafka consumer are empty
posting .jmx, avro schema and sample message for Kafka
[Jmeter.zip](https://github.com/corunet/kloadgen/files/5614017/Jmeter.zip)

and I`m using Classname .GenericKafkaSampler
if you connect ConfluentKafkaSampler then you get an error .NullPointerException: null

**Comment by kszosze** [comment]
Hi Vitaliee,
I´ll check it later today and come you back.

Cheers

**Comment by kszosze** [comment]
Hi @vitalee78 ,

I took a look into your problem I saw couple of thinks. 
a) an issue in the our generic serialiser which I fixed in the branch linked to this issue
b) a miss configuration in your JMX file. In order to add the Key into the message there was a flag name keyed.message which need to be enable ("YES" value) like the image attached
<img width="1032" alt="Screenshot 2020-12-01 at 01 03 11" src="https://user-images.githubusercontent.com/302714/100680247-6db79180-3371-11eb-954e-99a2606726bf.png">

I also took a look into your test plan file and fixed there.
[testPlan - Copy.jmx.txt](https://github.com/corunet/kloadgen/files/5619452/testPlan.-.Copy.jmx.txt)

Just remove the ".txt" and you will be able to try it.

Cheers!!

**Comment by vitalee78** [comment]
Hi, Jose!
Thank you very much, I`ll definitely try today.

**Comment by vitalee78** [comment]
Hi, Jose!
if  look through ./kafka-**avro**-console-consumer then a error
![2020-12-01 12_03_07-Window](https://user-images.githubusercontent.com/25228760/100719830-32977b80-33ce-11eb-9801-ba920f297864.png)
but on version 2.1.3 it worked in avro format

if  through  ./kafka-console-consumer then no errors

**Comment by kszosze** [comment]
HI Vitaliee,
my guess you are using the generic kafka sampler, that one only send the message as a normal Json so yo can read it with the normal kafka-console-consumer.. the schema is not sent and neither is serialised into an AVRO byte code.
KafkaSampler and Confluent does it. KafkaSampler allows you to choose which serialiser you want to use.
That solve your problem?
Cheers!

**Comment by vitalee78** [comment]
Hi, Jose!
Yes, I tried the probes.
if Confluent is just empty,
if Generic and KafkaSampler there is an error

**Comment by vitalee78** [comment]
Hi Jose!
I try Confluent, the message is not generated so the kafka is empty and the error is log Jmeter as follows
![ConfluentKafkaSampler](https://user-images.githubusercontent.com/25228760/100984036-34db1080-355b-11eb-9957-42536290637f.png)
and I use serialiser class - GenericRecordSerializer for key and value.serializer

If Kafka Sampler, the message is generated and sent to kafka, but the error in kafka-_avro_-console-consumer...  
![2020-12-03 11_47_59-Window](https://user-images.githubusercontent.com/25228760/100986165-e5e2aa80-355d-11eb-8d1d-ff9ad20865f4.png)

and there is still a message in the log Jmeter - WARN, but maybe it`s not critical?
![KafkaSampler](https://user-images.githubusercontent.com/25228760/100984827-41ac3400-355c-11eb-9d3c-ecdc2ead8195.png)

Help me understand what I'm doing wrong?

**Comment by kszosze** [comment]
HI @vitalee78 
is strange, can you please attach your latest test plan and current schema? I'll try to debug it and help you.

Cheers

**Comment by vitalee78** [comment]
[TestPlan_schema.zip](https://github.com/corunet/kloadgen/files/5634944/TestPlan_schema.zip)

**Comment by kszosze** [comment]
Hi Vitaliee,
May is a matter of configuration.. I can send messages without no problem with generic and kafka, Confluent is failing because it cannot solve the schema name, but this is issue of my setup I guess.

<img width="1157" alt="Screenshot 2020-12-03 at 11 29 01" src="https://user-images.githubusercontent.com/302714/100997607-c007d680-355a-11eb-9733-750fd89e1a93.png">
can you please try with this test plan?

[testPlan_KLoadGen.jmx.txt](https://github.com/corunet/kloadgen/files/5635435/testPlan_KLoadGen.jmx.txt)

I´m getting messages in the topic.....

<img width="1641" alt="Screenshot 2020-12-03 at 11 30 36" src="https://user-images.githubusercontent.com/302714/100997752-f8a7b000-355a-11eb-9d9f-cb55379fc476.png">

**Comment by vitalee78** [comment]
Hi kszosze!
you are not tired of me yet? ))

yes it also works for me if I look in kafka-console-consumer
and if you look in kafka-**avro**-console-consumer, then an error.
![2020-12-03 11_47_59-Window](https://user-images.githubusercontent.com/25228760/101126835-572d6680-360d-11eb-9527-31327207ecf4.png)

Our application reads in the topic in avro format and therefore I check in kafka-avro-console-consumer
Also the app reads the key / value message into the GenericRecordSerializer
if in the key  GenericRecordSerializer error
![error_avro_key](https://user-images.githubusercontent.com/25228760/101127270-44fff800-360e-11eb-8dd3-aabd9af8b869.png)

**Comment by kszosze** [comment]
Hi Vitaliee,
is not a problem help and not, I'm not tired of you.
What I'm seeing is you are using the same serialiser for key and value. That's the problem, Key is not an Avro document, so this serialiser should be use. Can you please change it back to the StringSerialiser one please?
_org.apache.kafka.common.serialization.StringSerializer_
I think that gonna work for you.
Cheers

**Comment by vitalee78** [comment]
yes, did the key in two versions - StringSerialiser works
And I realized that I misunderstood the task, talked to a colleague developer. Our application reads separately the key with its avro schema and the value with its avro schema
And I don’t understand, but what is the correct way to draw up a test plan and it is possible to do this in a plugin?
We need the key to be sent to avro too
[schemas.zip](https://github.com/corunet/kloadgen/files/5641666/schemas.zip)

**Comment by kszosze** [comment]
Well, that's unusual, key usually are not codec in avro unless you where using the confluent system. Can you try using the io.confluent.kafka.serializers.KafkaAvroSerializer serialiser for the key?

**Comment by vitalee78** [comment]
I tried with ...KafkaAvroSerializer for the key
![2020-12-04 12_57_06-Window](https://user-images.githubusercontent.com/25228760/101149754-6c67bc80-3630-11eb-8a80-157b4e8819e1.png)

**Comment by kszosze** [comment]
If you are using the confluent then your better option is go with the Confluent Sampler, it uses both confluent serialiser by default.. you tried that rigth? and give you some topic related issue?

**Comment by vitalee78** [comment]
Yes, tried  Confluent Sampler, also an error as in the last screenshot
and give me please some topic related issue

**Comment by kszosze** [comment]
Ok I'll take a look into it today with your example test plan and back to you asap.

**Comment by kszosze** [comment]
Ok I´m gonna need the key schema too in order to see why it´s not finding it the schema registry. Can you provide it also?
Cheers!

**Comment by vitalee78** [comment]
[schemas.zip](https://github.com/corunet/kloadgen/files/5646519/schemas.zip)
key schema and value schema

**Comment by kszosze** [comment]
Hi Vitaliee,
after saw your Key Schema I realize we cannot handle it now. But we can implement it, it will take a couple days.
Are you interested in this feature so we will implement it?

Cheers

**Comment by vitalee78** [comment]
Hi kszosze!
Yes, we interested in this feature!
Thank you!

**Comment by kszosze** [comment]
Privet Vitalee,

There is a branch linked to this ticket which a first approach for your request.
Is a breaking change, so you are gonna need to rewrite/tweak your test plan. 
I upload one as an example about how to use it with your provided schemas.
Wish this gonna work for you.
[TestPlans.jmx.txt](https://github.com/corunet/kloadgen/files/5669313/TestPlans.jmx.txt)
Cheers!!

**Comment by vitalee78** [comment]
Hi kszosze!
I will try to do it today

Thank you!

**Comment by vitalee78** [comment]
Hi kszosze!
trying to subtract testplan, error
![error_jmeter](https://user-images.githubusercontent.com/25228760/101860966-13dc7600-3b80-11eb-8c81-290fc250538a.png)

as I understood in the block
![block_xml](https://user-images.githubusercontent.com/25228760/101860978-1b038400-3b80-11eb-80fc-438dc373038b.png)

**Comment by kszosze** [comment]
Hi @Vitalie,
are you using this branch https://github.com/corunet/kloadgen/tree/%2368_adding_avro_key_support ?
Can you please upload the JMX?
Cheers

**Comment by vitalee78** [comment]
sorry, I used old release
It works and now I can see our message, but in the topic the message sent to String? 
because if you look in kafka-avro-console-consumer then the error
![2020-12-03 11_47_59-Window](https://user-images.githubusercontent.com/25228760/101893042-3ccb2e00-3bb5-11eb-894d-301b957a4d10.png)

if you look in a standard counsumer (kafka-console-consumer) it works fine
![string_topic](https://user-images.githubusercontent.com/25228760/101892972-1d340580-3bb5-11eb-868b-368278214251.png)

my JMX
[TestPlans - Copy.jmx.txt](https://github.com/corunet/kloadgen/files/5678634/TestPlans.-.Copy.jmx.txt)

**Comment by kszosze** [comment]
Ok i'll take a look asap

**Comment by kszosze** [comment]
Ok i see.. Let's gonna change the Test plan for something like this...
ConfluentkafkaSampler as Java Request Sampler
and  serializers should be io.confluent.kafka.serializers.KafkaAvroSerializer.

like this image

<img width="1251" alt="Screenshot 2020-12-11 at 12 22 53" src="https://user-images.githubusercontent.com/302714/101898087-d42b8380-3bab-11eb-9ac1-1da6d3b0925c.png">

then you can see something like 

![Screenshot 2020-12-11 at 12 25 23](https://user-images.githubusercontent.com/302714/101898240-0f2db700-3bac-11eb-8b78-8c7b402f9080.png)


using this command 

 kafka-avro-console-consumer --bootstrap-server kafka:9092 --topic matomo.matomo.matomo_log_action --group matomo

**Comment by vitalee78** [comment]
ok, I'll see it now

**Comment by vitalee78** [comment]
did, but I can't, there is an error on the jmeter side
message is not sent
![java_req](https://user-images.githubusercontent.com/25228760/101900768-18754e80-3bc1-11eb-8983-374823361d67.png)

![error_jmeter](https://user-images.githubusercontent.com/25228760/101900783-1dd29900-3bc1-11eb-90ce-c64a52faad47.png)

**Comment by kszosze** [comment]
Which version of JMeter are you using? It sounds  the plugin jar hasn't build properly. That class is added in the build process as a dependency. Can you please double check there is only one kloadgen-plugin-X.X.X.jar in the lib/ext folder

**Comment by kszosze** [comment]
Hi Vitaliee,
some new code had been merge in to master and bring it to this issue branch. There you will find a new Sampler, GenericBinaryKafkaSampler. Do you mind try this one?

Cheers!

**Comment by vitalee78** [comment]
yes, in the lib/ext folder  is only one, kloadgen-plugin-3.1.0.jar

and I try new code

**Comment by vitalee78** [comment]
I tried using GenericBinaryKafkaSampler but again the error is like in the last screenshot
it looks like I'm doing something wrong

**Comment by kszosze** [comment]
Well. does is really odd. Can you please send me yout apache-jmeter.... folder to my email jegarcia at corunet dot com

**Comment by vitalee78** [comment]
Hi Jose!
There was a conflict with another .jar, I removed it and there is no error

and reproduced another error, applied GenericBinaryKafkaSampler, GenericConfluentKafkaSampler and GenericKafkaSampler
also in the message the key missing {idaction: 123}

![error_avro](https://user-images.githubusercontent.com/25228760/101971651-17393580-3c44-11eb-96f3-16d6194bc5a8.png)

**Comment by kszosze** [comment]
well, we are getting better ... I'm asuming those errors are with the latest jmx file I sent to you or the one you sent to me or one new mix of both? I need to know in order to solve you problem.

Cheers!!

**Comment by vitalee78** [comment]
with my JMX
[TestPlans - Copy.jmx.txt](https://github.com/corunet/kloadgen/files/5687563/TestPlans.-.Copy.jmx.txt)

**Comment by kszosze** [comment]
I believe you are not using the latest version of that branch.. mainly because with just your jmx and only changing port of Schema Registry and Kafka brokers it give a good answer

<img width="1565" alt="Screenshot 2020-12-14 at 12 16 32" src="https://user-images.githubusercontent.com/302714/102075380-7050c700-3e06-11eb-9ecb-6551623a4a68.png">

**Comment by vitalee78** [comment]
I using this branch - https://github.com/corunet/kloadgen/tree/%2368_adding_avro_key_support, right?

**Comment by kszosze** [comment]
That's the right one. Just was a merge problem with latest changes in Master. I just fix and push them. Can you try it.
Sorry for that.

**Comment by vitalee78** [comment]
yes, it works right now!

though for some reason in the 'View Results Tree' report there is red text, but there are no errors in the kafka there are messages in avro
![red_tree](https://user-images.githubusercontent.com/25228760/102084967-04cb2180-3e27-11eb-93a3-778320cbedcf.png)

at the moment it suits us, thanks!

**Comment by kszosze** [comment]
Red means There is an error during the process. Please check the response, it should show the broker answer.

**Comment by kszosze** [comment]
Hi Vitaliee,
any news about the red thing or this branch let's you run your tests?
Cheers

**Comment by vitalee78** [comment]
Hi, Jose!
our testing is working fine now,
but with red text, I did not find the reason, during load I disable this report

**Comment by kszosze** [comment]
Strange, may be in the response data you can find some answers.
I'll close this issue then.
Cheers

**Comment by vitalee78** [comment]
in the response data - topic: name_topic, partition: 0, offset: 2358125

**Comment by kszosze** [comment]
Forget it.. it was a tiny error in the response build. Is gonna be fixed in the next commit.
Sorry and thanks for the feedback!

**Comment by vitalee78** [comment]
ok, 
that is, then I can take the build from the master?

**Comment by kszosze** [comment]
Once I'll do the merge.. for now all changes are over the branch

**Comment by vitalee78** [comment]
ok,
thank you for the work done, now we are using it for our tasks.
we have another point when generating data, but this is not critical, so maybe we will turn again
