### ISSUE TITLE
Kafka File Load Generator Config Element Issue and Errors

### ISSUE THREAD

**Issue by raheelazhar1** [corunet/kloadgen#77]
Hi,

First of all, thanks for building this wonderful plugin! I have used it successfully for some cases but seeing few issues:

1- I've built the Jar but it's missing Kafka File Load Generator Config. Does it have any prerequisites?
2- When I use Schema Registry Config Element (successfully), and Value Schema Load Generator Config, my Java request throws "error serializing avro message".
3- I changed the approach and removed "Schema Registry Config Element",  and tried using "Schema File Load Generator Config" instead. With this element, my producer "net.coru.kloadgen.sampler.KafkaSampler" throws this error:
net.coru.kloadgen.exception.KLoadGenException: Unsupported Serializer

Can you please help??
Thanks,
Raheel

**Comment by raheelazhar1** [comment]
![Uploading image.png…]()

**Comment by raheelazhar1** [comment]
![Uploading image.png…]()

**Comment by raheelazhar1** [comment]
![image](https://user-images.githubusercontent.com/76075810/103871367-9890b600-5092-11eb-8cef-0d5776e67357.png)

**Comment by raheelazhar1** [comment]
![image](https://user-images.githubusercontent.com/76075810/103871466-b0683a00-5092-11eb-8532-bcec29405266.png)

**Comment by raheelazhar1** [comment]
Omitted the field names for privacy's sake.

**Comment by raheelazhar1** [comment]
![image](https://user-images.githubusercontent.com/76075810/103872567-3933a580-5094-11eb-99ac-191a1cfd94e5.png)

**Comment by raheelazhar1** [comment]
![image](https://user-images.githubusercontent.com/76075810/103872732-6aac7100-5094-11eb-8a98-c0b58e539ca0.png)

**Comment by raheelazhar1** [comment]
![image](https://user-images.githubusercontent.com/76075810/103872950-b101d000-5094-11eb-8df2-933b5e0cf35d.png)

**Comment by raheelazhar1** [comment]
When I leave the subject fields blank under Value Schema Load Generator Config, it passes with blank payload. The problem seems to be my payload. BTW, our Schema format is Avro.

**Comment by codigoFuentes** [comment]
Hi raheelazhar1.
Can you send me an example schema? I'm only interested in the structure of the schema for testing.

**Comment by raheelazhar1** [comment]
Hi codigoFuentes,



![Uploading image.png…]()

**Comment by raheelazhar1** [comment]
![image](https://user-images.githubusercontent.com/76075810/104025649-927e0080-518a-11eb-8e9d-4b141158ba23.png)

**Comment by raheelazhar1** [comment]
And this is what's sent in the request:

![image](https://user-images.githubusercontent.com/76075810/104025983-fa344b80-518a-11eb-81da-b609c66073c8.png)

**Comment by raheelazhar1** [comment]
And this is what's sent in the request:

![image](https://user-images.githubusercontent.com/76075810/104026105-1f28be80-518b-11eb-989e-3b0083f3a702.png)

**Comment by codigoFuentes** [comment]
To debug your example I need a schema with the same structure that you are using for example like this https://github.com/corunet/kloadgen/blob/master/avro-example.avsc.

**Comment by raheelazhar1** [comment]
{
  "nm": "MyClass",
  "type": "record",
  "nmspace": "com.acme.avro",
  "fields": [
    {
      "nm": "customerbio",
      "type": {
        "nm": "customerbio",
        "type": "record",
        "fields": [
          {
            "nm": "countryOfBirthCountryCode",
            "type": "string"
          },
          {
            "nm": "dateOfBirth",
            "type": "string"
          },
          {
            "nm": "bioExtensionAttribute",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          },
          {
            "nm": "emailAddress",
            "type": {
              "type": "array",
              "items": {
                "nm": "emailAddress_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "emailAddress",
                    "type": "string"
                  },
                  {
                    "nm": "startDate",
                    "type": "string"
                  },
                  {
                    "nm": "lastVerifiedDate",
                    "type": "string"
                  },
                  {
                    "nm": "type",
                    "type": "string"
                  },
                  {
                    "nm": "contactPreference",
                    "type": {
                      "type": "array",
                      "items": {
                        "nm": "contactPreference_record",
                        "type": "record",
                        "fields": [
                          {
                            "nm": "optIn",
                            "type": "string"
                          },
                          {
                            "nm": "type",
                            "type": "string"
                          }
                        ]
                      }
                    }
                  }
                ]
              }
            }
          },
          {
            "nm": "IdDocument",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          },
          {
            "nm": "auditEvent",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          },
          {
            "nm": "MemCert",
            "type": {
              "type": "array",
              "items": {
                "nm": "MemCert_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "primaryIndicator",
                    "type": "string"
                  },
                  {
                    "nm": "activationDate",
                    "type": "string"
                  },
                  {
                    "nm": "MemNumber",
                    "type": "string"
                  },
                  {
                    "nm": "type",
                    "type": "string"
                  }
                ]
              }
            }
          },
          {
            "nm": "followeringcustomerID",
            "type": {
              "type": "array",
              "items": {
                "nm": "followeringcustomerID_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "poefollowerionID",
                    "type": "string"
                  },
                  {
                    "nm": "role",
                    "type": "string"
                  },
                  {
                    "nm": "trancustomerID",
                    "type": "string"
                  },
                  {
                    "nm": "customerbioID",
                    "type": {
						"type": "array",
						"items": "string"
			 
					},
					"default": null
                  }
                ]
              }
            }
          },
          {
            "nm": "note",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          },
          {
            "nm": "nm",
            "type": {
              "type": "array",
              "items": {
                "nm": "nm_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "firstnm",
                    "type": "string"
                  },
                  {
                    "nm": "lastnm",
                    "type": "string"
                  },
                  {
                    "nm": "lastVerifiedDate",
                    "type": "string"
                  }
                ]
              }
            }
          },
          {
            "nm": "phNumber",
            "type": {
              "type": "array",
              "items": {
                "nm": "phNumber_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "countryDialInNumber",
                    "type": "string"
                  },
                  {
                    "nm": "phNumber",
                    "type": "string"
                  },
                  {
                    "nm": "startDate",
                    "type": "string"
                  },
                  {
                    "nm": "lastVerifiedDate",
                    "type": "string"
                  },
                  {
                    "nm": "type",
                    "type": "string"
                  },
                  {
                    "nm": "contactPreference",
                    "type": {
                      "type": "array",
                      "items": "contactPreference_record"
                    }
                  }
                ]
              }
            }
          },
          {
            "nm": "contactPreference",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          },
          {
            "nm": "customerbioID",
            "type": {
              "type": "array",
              "items": {
                "nm": "customerbioID_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "updatedDate",
                    "type": "string"
                  },
                  {
                    "nm": "bioID",
                    "type": "string"
                  },
                  {
                    "nm": "startDate",
                    "type": "string"
                  },
                  {
                    "nm": "type",
                    "type": "string"
                  }
                ]
              }
            }
          },
          {
            "nm": "permAddress",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          }
        ]
      }
    }
  ]
}

**Comment by raheelazhar1** [comment]
@codigoFuentes , here you go..

{
  "nm": "MyClass",
  "type": "record",
  "nmspace": "com.acme.avro",
  "fields": [
    {
      "nm": "customerbio",
      "type": {
        "nm": "customerbio",
        "type": "record",
        "fields": [
          {
            "nm": "countryOfBirthCountryCode",
            "type": "string"
          },
          {
            "nm": "dateOfBirth",
            "type": "string"
          },
          {
            "nm": "bioExtensionAttribute",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          },
          {
            "nm": "emailAddress",
            "type": {
              "type": "array",
              "items": {
                "nm": "emailAddress_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "emailAddress",
                    "type": "string"
                  },
                  {
                    "nm": "startDate",
                    "type": "string"
                  },
                  {
                    "nm": "lastVerifiedDate",
                    "type": "string"
                  },
                  {
                    "nm": "type",
                    "type": "string"
                  },
                  {
                    "nm": "contactPreference",
                    "type": {
                      "type": "array",
                      "items": {
                        "nm": "contactPreference_record",
                        "type": "record",
                        "fields": [
                          {
                            "nm": "optIn",
                            "type": "string"
                          },
                          {
                            "nm": "type",
                            "type": "string"
                          }
                        ]
                      }
                    }
                  }
                ]
              }
            }
          },
          {
            "nm": "IdDocument",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          },
          {
            "nm": "auditEvent",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          },
          {
            "nm": "MemCert",
            "type": {
              "type": "array",
              "items": {
                "nm": "MemCert_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "primaryIndicator",
                    "type": "string"
                  },
                  {
                    "nm": "activationDate",
                    "type": "string"
                  },
                  {
                    "nm": "MemNumber",
                    "type": "string"
                  },
                  {
                    "nm": "type",
                    "type": "string"
                  }
                ]
              }
            }
          },
          {
            "nm": "followeringcustomerID",
            "type": {
              "type": "array",
              "items": {
                "nm": "followeringcustomerID_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "poefollowerionID",
                    "type": "string"
                  },
                  {
                    "nm": "role",
                    "type": "string"
                  },
                  {
                    "nm": "trancustomerID",
                    "type": "string"
                  },
                  {
                    "nm": "customerbioID",
                    "type": {
						"type": "array",
						"items": "string"
			 
					},
					"default": null
                  }
                ]
              }
            }
          },
          {
            "nm": "note",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          },
          {
            "nm": "nm",
            "type": {
              "type": "array",
              "items": {
                "nm": "nm_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "firstnm",
                    "type": "string"
                  },
                  {
                    "nm": "lastnm",
                    "type": "string"
                  },
                  {
                    "nm": "lastVerifiedDate",
                    "type": "string"
                  }
                ]
              }
            }
          },
          {
            "nm": "phNumber",
            "type": {
              "type": "array",
              "items": {
                "nm": "phNumber_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "countryDialInNumber",
                    "type": "string"
                  },
                  {
                    "nm": "phNumber",
                    "type": "string"
                  },
                  {
                    "nm": "startDate",
                    "type": "string"
                  },
                  {
                    "nm": "lastVerifiedDate",
                    "type": "string"
                  },
                  {
                    "nm": "type",
                    "type": "string"
                  },
                  {
                    "nm": "contactPreference",
                    "type": {
                      "type": "array",
                      "items": "contactPreference_record"
                    }
                  }
                ]
              }
            }
          },
          {
            "nm": "contactPreference",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          },
          {
            "nm": "customerbioID",
            "type": {
              "type": "array",
              "items": {
                "nm": "customerbioID_record",
                "type": "record",
                "fields": [
                  {
                    "nm": "updatedDate",
                    "type": "string"
                  },
                  {
                    "nm": "bioID",
                    "type": "string"
                  },
                  {
                    "nm": "startDate",
                    "type": "string"
                  },
                  {
                    "nm": "type",
                    "type": "string"
                  }
                ]
              }
            }
          },
          {
            "nm": "permAddress",
            "type": {
              "type": "array",
              "items": "string"
			 
            },
			"default": null
          }
        ]
      }
    }
  ]
}

**Comment by codigoFuentes** [comment]
We are working with your example, we hope to give you a solution as soon as possible

**Comment by raheelazhar1** [comment]
Thanks @codigoFuentes . Looking forward to hearing from you..

**Comment by codigoFuentes** [comment]
HI @raheelazhar1 
Reviewing your schema we have verified that the problem is in the default null values in the array types. You can solve it by removing the default null values from your schema or by defining them as UNION and assigning them a null array as the default value.

**Comment by codigoFuentes** [comment]
You can try the new version 3.3.0

**Comment by raheelazhar1** [comment]
Thanks @codigoFuentes . I'll give it a try and let you know.

**Comment by codigoFuentes** [comment]
Hi @raheelazhar1
Have you been able to try it?

**Comment by raheelazhar1** [comment]
Hi @codigoFuentes ,

I upgraded to 3.3.0, but that didn't help. However, I am working on the two solutions proposed by you (changing array type etc.). I don't have rights to change the Schema, so it might take few days.

Thanks,
Raheel
