### ISSUE TITLE
Issue while passing the field value containing comma

### ISSUE THREAD

**Issue by pragya295** [corunet/kloadgen#78]
Hi team, thank you for this plugin it helped a lot.

I am facing an issue while passing the below field value in the payload. 

Field Type: **String**
Filed Value:   **[{"client_code":"ABC"\,"market_codes":["popfa"]\,"permissions":[{"app_code":"TEAA"\,"resource_codes":[{"code":""\,"action":""}]}]}]**

this string gets break from comma and I only able to get half string in the output 

**[{"client_code":"ABC"\**

can you please help me with the same how I can pass comma in the string?

![image](https://user-images.githubusercontent.com/58456453/103984932-0382df80-51ae-11eb-9921-0c400e6eed56.png)

**Comment by kszosze** [comment]
hi @pragya295,
that field was never designed to contain json objects, so we treat all the values as single ones. Do you really need to support json objects there? It looks like you payload should be an object/record itself.
Cheers

**Comment by pragya295** [comment]
Yes, I do need support for json object is that possible ? The payload is implemented in this format only.

**Comment by kszosze** [comment]
HI @pragya295,
It can be, I will take couple of days since I need this to fit in our roadmap. But we will try.
Cheers!

**Comment by kszosze** [comment]
HI @pragya295,
We are delivering a possible solution in a branch for this issue. Do you mind test if that works for you?
Cheers

**Comment by pragya295** [comment]
Hi @kszosze,
Thanks for the update. I will try this and update you in sometime. 
Cheers

**Comment by pragya295** [comment]
Hi @kszosze,
I have tried the above thing but still getting the same, 

Settings used in script:

![image](https://user-images.githubusercontent.com/58456453/104176438-3f77a800-542d-11eb-9073-d6dddde43a5d.png)
![image](https://user-images.githubusercontent.com/58456453/104176450-44d4f280-542d-11eb-8460-e48e82090894.png)

Output
![image](https://user-images.githubusercontent.com/58456453/104176610-8cf41500-542d-11eb-8854-563631764cda.png)

**Comment by kszosze** [comment]
Hi @pragya295,
I saw a double "[" in the "value schema load config" element, just add the json objects separated by ",". We don't expect you add an array as object.
Other option is if you use JMeter Context Variables in there.. just with "${<Variable name>}" will work
Cheers

**Comment by pragya295** [comment]
I have passed below json string 

{"client_code":"pre", "market_codes":["zfhj"], "permissions":[{"app_code":"yuy", "resource_codes":[{"code":"jj", "action":"hkhk"}]}]}

still not working. 

one pair of these [ ] brackets are added automatically as soon as we click outside the field. It's not added by me. Same is for JMeter Context Variables, brackets get added and its displays like [${variable name}]

![image](https://user-images.githubusercontent.com/58456453/104275257-75b63580-54c8-11eb-9eef-91d6e0f75da0.png)

**Comment by kszosze** [comment]
Hi @pragya295,
one pair or square brackets are added by default, but I saw 2 in the screenshot.. no worries.. I´ll take a look into it.

**Comment by kszosze** [comment]
Hi @pragya295,
made some changes, can you try this branch? Keep on eye in plugin version I bumped it because the changes, so remember to clean up previous jar.
Cheers.

**Comment by pragya295** [comment]
HI @kszosze,
This change worked for me.

Thank you so much for your support. 

Should I close this ticket from my end ?

**Comment by kszosze** [comment]
HI @pragya295,
no worries It will be close once I merge the changes into master.
Thanks!!
