### ISSUE TITLE
Getting Error while passing string-array

### ISSUE THREAD

**Issue by pragyasingh2905** [corunet/kloadgen#89]
Hi, 
I am trying to pass string-array field in the schema and getting below error can you please help me with the same.

![image](https://user-images.githubusercontent.com/69038587/110900679-273ae100-8329-11eb-91ee-62731618c42e.png)

![image](https://user-images.githubusercontent.com/69038587/110900711-3457d000-8329-11eb-9de3-f020c0e3021f.png)

**Comment by kszosze** [comment]
Hi @pragyasingh2905,

This is know error; was detected a few days ago and current Pull Request for branch #86 should solve it. Do you mind try that branch?
Cheers

**Comment by pragyasingh2905** [comment]
sure, let me try will update you soon. thanks

**Comment by pragyasingh2905** [comment]
Hi @kszosze, this how I passed the value in schema and getting error. am I doing something wrong here?

![image](https://user-images.githubusercontent.com/69038587/110923867-5f511c80-8347-11eb-9499-8ec897670e7b.png)

**Comment by kszosze** [comment]
Hi @pragyasingh2905,
Can you send me your schema? or if you can't by asl, can you provide something similar so I can test it and fix it?
Thanks!

**Comment by pragyasingh2905** [comment]
Hi @kszosze, here it is
{
   "header": {
      "name": "Demo",
      "version": "V1",
      "publishTime": 1614758239442,
      "producerId": "XYZ"
   },
   "payload": {
      "correlationId": "correlation_Id",
      "templateId": "7fsdyfdsf7dfysi8df",
      "clientCode": "Demo",
      "tenantId": null,
      "subTenantId": null,
      "subURI": "xyz",
      "emails": [
         "pragya.singh@gmail.com"
      ],
      "contextData": "{\"clientcode\":\"test\",\"clientCode\":\"test\",\"notification_emails\":\"pragya.singh@gmail.com\",\"templateId\":\"7fsdyfdsf7dfysi8df\"}
   }
}

please let me know if anything else is required. thanks

**Comment by kszosze** [comment]
Hi @pragyasingh2905,
that is the generated example, what I need is the schema used to generate the data. I need to know is defined that emails field, looks like there is the problem.
Cheers!

**Comment by pragyasingh2905** [comment]
Hi @kszosze below is the schema.... thanks
{
  header: {
    name: "xyz";
    version: String;
    publishTime: Long;
    producerId: String;
  };
  payload: {
    correlationId: String;
    templateId: String;
    clientCode: Nullable<String>;
    tenantId: Nullable<String>;
    subTenantId: Nullable<String>;
    subURI: Nullable<String>;
    emails: Nullable<String[]>;
    contextData: String;
  };
}

**Comment by kszosze** [comment]
Hi @pragyasingh2905,
I think we have a comunication issue. I need your AVRO schema, JSchema or Json-Schema file in order to see what is happening. That schema you sent to me is not supported by the pluggin.
Cheers

**Comment by pragyasingh2905** [comment]
Hi @kszosze this is what we are using email is going as emails: Nullable<String[]> input and this is what "emails": ["pragya.singh@gmail.com"], get in output... I don't know what else to share.... should I share jmx file with you.

**Comment by kszosze** [comment]
Hi @pragyasingh2905,
Get this jmx will help for sure to understand the issue.
Cheers!

**Comment by pragyasingh2905** [comment]
Hi @kszosze,
I am unable to attach the file can you please download it from this link 

https://drive.google.com/file/d/1veyUZezEy2bBDpQBImvkTYPhXRPPKprP/view?usp=sharing

thanks,

**Comment by kszosze** [comment]
Hi @pragyasingh2905,
There is a branch #89 with a fix for that issue, can you try it?.
[Schema and Plan](https://github.com/corunet/kloadgen/files/6177384/Archive.zip)
I recreate the AVRO Schema following your example you provide in your jmx. Hope it's the same.
Cheers

**Comment by pragyasingh2905** [comment]
Hi @kszosze ,
sure let me try it and get back to you..
thanks

**Comment by pragyasingh2905** [comment]
Hi @kszosze,
the above fix working for me.. thanks for your help.
