### ISSUE TITLE
Cannot disable ssl.endpoint.identification.algorithm

### ISSUE THREAD

**Issue by raph007** [corunet/kloadgen#90]
Hi,

I'm trying to disable it by setting empty:

![image](https://user-images.githubusercontent.com/755617/111907958-afbb2f00-8a57-11eb-8fb0-fa2461324d06.png)

By after that, when I press "Start" in JMeter, it just restores to default value:

![image](https://user-images.githubusercontent.com/755617/111908001-d1b4b180-8a57-11eb-8704-86f43a5f84a0.png)

I'm using plugin from "master" branch and JMeter 5.4 on Mac.

Any ideas what could the problem?

**Comment by kszosze** [comment]
Hi @raph007 ,
unfortunately this a weird behaviour from JMeter GUI, about how the component we use for configure the samplers works.
I will need to tweak that by code. 
I'll prepare a fix asap.
Cheers!

**Comment by kszosze** [comment]
Hi @raph007,
I have a branch with a possible fix for your issue.
If you don't mind to test it?
Cheers!!!

**Comment by raph007** [comment]
Hi @kszosze,

Thank you for quick response.

I've just tested it and it works ok. :)
