### ISSUE TITLE
Unable to generate numbers more than 10 characters 

### ISSUE THREAD

**Issue by Tanmayghosh** [corunet/kloadgen#93]
Field type having Long or Int with field length 11 or more is generating only 10 digits long value

**Comment by kszosze** [comment]
Hi @Tanmayghosh 
I´ll look into it. 
Thanks!

**Comment by kszosze** [comment]
Hi @Tanmayghosh,

I have branch with a possible fix. Do you mind to verify if it works for you?

Cheers.
